- .gitignore
- winutil.ps1
Closes #15 
- Adds Check if winget is installed
- If not installed, checks if the computer is running 1809+ and if the computer is running Windows Server or LTSC
- If running pre-1809, winget install stops as it is not supported
- If running Windows Server or Windows LTSC, runs an alternative installer compatible with those editions of Windows
> Add winget check and installer

- .gitignore
- winutil.ps1
1. Use Curl to download O&O Shutup.
2. Set MenuDelay to `1`. With `0` Windows will simply use the default value of 400.
> Small Fixes.

- winutil-test.ps1
I created a sample of how I do runspaces in the scripts I have out in production. I like to keep the main form inside the initial thread and call runspaces from there. Not as pretty but I also don't use the xaml files like you do.
> WIP: Runspaces

- winutil.ps1
- Closes #39
- $arch is not set to a value in the script; thus it throws an error when the If-Statement is called
- Fixed by replacing the $arch variable check with a wmic check
> Fix bug in #39

- MainWindow.xaml
- winutil.ps1
- Pull Request #19 didn't add an entry for PanelDISM into MainWindow.xaml, causing an error to be thrown when the script is executed and a button to not be created
- Fixed by adding an entry into MainWIndow.xaml that creates the needed button under the FixesUpdate button
- Note: To see the fix, you need to comment line 9 and uncomment line 8 to use the local MainWindow.xaml instead of the one in the Main Branch
- Fixed formatting
- Added /scan to chkdsk so it attempts to fix corruption on online drives
- Tweaked Write-Host's
- Added newlines (`n) to space out the Statuses
- Added progress indicators
- Required "s and 's to be swapped so x/4 does not perform an operation
> Fix and Tweak #19

- MainWindow.xaml
- winutil.ps1
Reverts ChrisTitusTech/winutil#29
> Revert "Added Uncheck all button in the Install tab"

- winutil-test.ps1
- Fixed a few spelling errors
- dependancies -> dependencies
- Evnronment -> Environment
- haved -> have
- Hibernte -> Hibernate
- histroy -> history
- extentions -> extensions
> Fix a few spelling errors

- winutil-test.ps1
This is a very simple if statement, I don't think there's much to explain
```PowerShell
if ($IsLinux){ # PowerShell on Linux has that read-only bool variable set to $true
Write-Host "This utility is exclusively designed for Windows"
return
}
```
> Add a check for $isLinux

- winutil.ps1
Hello Chris,
What did i change?
So instead of using EnableLUA to 0, im using the Method of Disabling the Prompt for Admin Users.
What im doing here is changing HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System to 0 (5 is default)
Why do you ask?
Some tools tend to break or you maybe want someone else to use your PC.
It is annoying to be alerted by certain Programs to ,,Your UAC is turned off,, and this works around that completly.
Tldr
If you find a way to edit Group Policy via Powershell it makes this way Easier.
All im doing is changing this value here.
> Added Disable UAC

- README.md
- winutil.ps1
Right at the end of applying the misc tweaks there's an error when you try to set a boolean value to `false`.
I leave the error log here.
```
Adjusting visual effects for performance...
Adjusted visual effects for performance
false:
Line |
964 |              $WPFMiscTweaksDisplay.IsChecked = false
|                                                ~~~~~
| The term 'false' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
> Fix invalid flag value after applying misc tweaks

- winutil.ps1
Added Nahimic Service to list of services to set to manual. Nahimic seems to provide little improvement to audio for some resources consumed and tends to cause issues with specific games. Comes preinstalled on lots of prebuilts and laptops.
> Add Nahimic Service

- winutil.ps1
Registry values were not changing after applying GameDVR tweaks. Because all the registry tweaks were under if condition in the code. Modified that and now working properly.
> Fixed GameDVR Code

- winutil.ps1
Gamebar Presence Writer causes stutter in games, while running in
background.
Deactivated the trigger of Gamebar Presence Writer to resolve this issue.
> Disable Gamebar Presence Writer

- MainWindow.xaml
- winutil.ps1
Added option for set classic right click menu under tweak section
also added into undo tweaks for restore default right click menu layout
also fix disable notification variable name 
i tested both features on different windows 11 vm multiple times its works fine
> Added option for set classic right click menu

- MainWindow.xaml
- winutil.ps1
Adds toggle for System dark mode as well as App Dark mode to Tweaks. This is to fix issue https://github.com/ChrisTitusTech/winutil/issues/354 . Tested and Working on Windows 10 22H2. Was unable to figure out how to add the functionality to the current buttons so I made new buttons for system and renamed the current buttons to specify App dark mode. Feel free deny merge and do it better if you want as i have no clue how to use github properly and this is my first pull req. Fixed #357 (based on wrong branch sorry)
> Add Toggle for System Dark Mode

- pester/winutil.Tests.ps1
- runspace.ps1
- winutil.ps1
I updated the logic to split the semi colon as this was missed in the original implementation of the Get-Checkboxes function. I also updated the logic to only pass unique values.
Also updated the unit tests to detect if duplicate values there.
#401
> Fix multiple winget entry in json file

- winutil.ps1
@ChrisTitusTech looks like when I updated the applications json for choco the install group got removed and I missed that. Apologies on that. 
Also looks like the pester test got messed up with all the merge requests. I will look into that.
> Hotfix fix Get-Checkboxes function

- MainWindow.xaml
- winutil.ps1
Don't close this commit again without properly looking at it. I've corrected your spelling of Cloudflare. In your code you have it spelled as "Cloud Flare" I have changed this to now be "Cloudflare" as seen in the official naming.
> Fixed Cloudflare Naming

- winutil.ps1
I moved the "DiagTrack" service code from lines #673-639 down to just before the related "Removing AutoLogger file and restricting directory..." section. Seemed best to stop/disable the service since it messes with the Autologer directory while its running. Lastly, I removed the second stop/disable code on lines #738-740.
> Removed Duplicate Stop/Disable DiagTrack Service Code

- winutil.ps1
Setting Computer\HKEY_CURRENT_USER\Control Panel\Mouse\MouseHoverTime needs to be REG_SZ instead of REG_DWORD as suggested by [meky84](https://github.com/meky84) in issue #516. With the wrong type the Taskbar and the Start Menu become hard to use because everything pops up instantly, probably because it's then treated as a 0 ms delay.
This fixes issue #516.
> Fix data type of MouseHoverTime

- winutil.ps1
the current registry key value doesn't work for me, looking around
https://www.winhelponline.com/blog/enable-numlock-login-screen-default/
> Set it to 2 (for Windows 7)
Set it to 80000002 (for Windows 8 and Windows 10)
using 80000002 did work for me, and since this tool is for windows 10 and 11 I see no point in using the value for win 7
> fix enable numlock after startup

- scripts/main.ps1
Noticed darkmode was not toggling, looks like it doesn't get picked up by the following line as the dark mode toggle is considered a checkbox and not a button. Will have to think of a way to pull those in automatically. Easiest way might be using a naming convention to pull all checkboxes that use that style.
https://github.com/ChrisTitusTech/winutil/blob/a1c7501b98d56c5b554f9cfe70cb5a0767385796/scripts/main.ps1#L48
> Fix DarkMode

- config/tweaks.json
- winutil.ps1
Hi Chris,
I found a bug in OOSU10. The .cfg file was corrupted because there was a wrong link to ooshutup10_winutil_settings.cfg.
> [ooshutup10] Fixed link to ooshutup10 settings file

- config/applications.json
- xaml/inputXML.xaml
Issue #690 requested Neovim and Node Version Manager (NVM), so this commit will add those packages as installable programs.
Edited `applications.json`:
- added the correct package names for em 
Edited `inputXML.xml`:
- Just added Node Version Manager and Neovim under the Development section
> Add Neovim and Node Version Manager

- config/tweaks.json
- winutil.ps1
The `AllowGameDVR` regkey not only prevents GameDVR, but it also stops the hotkeys for Xbox Game Bar.
Winkey+G and Xbox Controller -> Xbox Button will not work when this key is set to 0.
I propose splitting this key into its own category. By keeping this separate, a user who wants it completely off can still enable this key.
Resolves:
#638
#371
#595
Worth noting to get GameBar working again on machines that already ran the Disable DVR script must:
1. Change the AllowGameDVR regkey to 1:  
`Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR" -Name "AllowGameDVR" -Type DWord -Value 1`
2. Reboot PC
3. Explicitly Toggle ON the option in Settings -> Gaming -> Xbox Game Bar
--------
This moves the AllowGameDVR reg edit to its own category. 
There is plenty of use cases …
> Split up AllowGameDVR to fix breaking Xbox Game Bar

- config/tweaks.json
- winutil.ps1
- xaml/inputXML.xaml
Enable or disable verbose sign in status messages. Verbose status messages may be helpful when you are troubleshooting slow startup, shutdown, logon, or logoff behavior.
> add verbose logon

- Compile.ps1
- config/applications.json
- config/themes.json
- functions/private/Set-WinUtilUiTheme.ps1
- functions/public/Invoke-WPFUltimatePerformance.ps1
- scripts/main.ps1
- winutil.ps1
- xaml/inputXML.xaml
We need to figure out how to expose themes to the user. I've added a contrast theme that is more friendly for people with vision issues, called matrix. In order to see it open main.ps1 and change 'classic' theme to 'matrix'.  Recompile winutil.ps1 and launch it
Here is an example of that theme:
> New Theme support, initial functions. 

- config/applications.json
- winutil.ps1
- xaml/inputXML.xaml
- Previous installing snappy driver installer origin with winget gives error : installer hash not matched. and it failed installtion.
- Now i made PR to fix this and upgrade version of sdio on [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs/) with PR : https://github.com/microsoft/winget-pkgs/pull/115287. 
- It fix the issue and now when we install sdio with following command : `winget install GlennDelahoy.SnappyDriverInstallerOrigin` it works fine. after installtion we can run sdio with `sdio` command.
Done FR : #642
> Added snappy driver installer origin 

- functions/public/Invoke-WPFUpdatesdefault.ps1
- functions/public/Invoke-WPFUpdatessecurity.ps1
As I tested, if you add it command via cmd, it adds without space even if there is a space in the property name, and everything is fine
`reg add "HKLM\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" /v "DeferQualityUpdatesPeriodInDays " /t REG_DWORD /d 4 /f`.
But if you use powershell, the property name will have a space in the property name and it won't work
`Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" -Name "DeferQualityUpdatesPeriodInDays " -Type DWord -Value 4`.
I fixed it
`Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\WindowsUpdate\UX\Settings" -Name "DeferQualityUpdatesPeriodInDays" -Type DWord -Value 4`.
> remove unnecessary space from property name

- README.md
I thought that I would add a video you made on your YouTube channel which perfectly explains the usage of your toolbox through your mouth. This could be useful for users who don't want to read the README but still want to set up their system efficiently. The size of the thumbnail can be modified using `default`, `mqdefault`, `hqdefault` or `sddefault` so do let me know if you don't like its size and I can change it.
> Add CTT YouTube tutorial video to README

- config/applications.json
Small issue in the naming of TCPView in the `config/applications.json` winget line which caused the application not to be found when trying to install it. 
The line was `"winget": "Microsoft.Sysinternals.Tcpview",` when it should have been `"winget": "Microsoft.Sysinternals.TCPView",`, small error and an easy fix which I saw while watching the new video.
P.S: *This is my first PR here and I hope I did it correctly*.
> Incorrect WinGet ID for TCPView.

- config/applications.json
- xaml/inputXML.xaml
Adds install option for ZeroTier One to Utilities menu. Refer to Issue #1052.
ZeroTier One is a popular, easy to configure VPN utility with an extremely generous free tier.
All compiles, installs & runs OK on my tests.
> Add ZeroTier One to utilities menu

- functions/public/Invoke-WPFShortcut.ps1
- gpedit-home.ps1
- winutil.ps1
Replaced `C:\Windows`  to environment variable for Windows directory, for compatibility if Windows is installed with a different drive letter.
> replacing the hard-coded paths for windows dir

- config/applications.json
Edited application.json to have the version of python updated to the new 3.12 for winget. Choco should work without any changes.
> Changed version of python for winget to 3.12

- config/preset.json
- config/tweaks.json
- functions/private/Get-WinUtilToggleStatus.ps1
- functions/private/Invoke-WinUtilDarkMode.ps1
- functions/private/Invoke-WinUtilMouseAcceleration.ps1
- functions/private/Invoke-WinUtilNumLock.ps1
- functions/private/Invoke-WinUtilShowExt.ps1
- functions/private/Invoke-WinUtilVerboseLogon.ps1
- functions/public/Invoke-WPFButton.ps1
- functions/public/Invoke-WPFToggle.ps1
- winutil.ps1
- xaml/inputXML.xaml
- Added new section for basic configuration settings : customize preferences.
- converted basic tweaks that previously occupy  two checkboxes (for enable and disable ) into toggle button
(numlock on start, verbose logon messages, show file extensions, mouse acceleration).
- move dark theme and bing search in start menu tweaks into customize preferences section.
- manor changes like :  tooltip for tweaks and gui one line arrangements for toggle buttons and combobox for dns.
- add custom sytle for toggle button called 'ColorfulToggleSwitchStyle'  in xaml file (note: old style code 'ToggleSwitchStyle' is still there but not using).
- add custome style for toggle tweaks label 'labelfortweaks' that mimic the style of checkbox so tweaks that are using toggle button matches the style with rest …
> New Section: Customize  Preferences (inside tweaks section)

- config/applications.json
- xaml/inputXML.xaml
Hello!
I'd like to suggest adding Session messenger as an install option.
Session (https://getsession.org/ )is an open source messenger app that:
- uses onion routing for messages
- does not require phone number to use it
- have similair features to Signal
- is secure and private
> Add Session messenger to the applications list.

- winutil.ps1
- xaml/inputXML.xaml
"Extensions" was misspelled as "Extentions" in a couple places.
> fixed typo in a few places.

- functions/private/Get-LocalizedYesNo.ps1
I tried to use MicroWin to create a compact image, however, I encountered the following error.
I had to do some research, which revealed the problem that on my localization (ru) the help has only 2 spaces instead of 3.
This caused an error that did not allow to return values for Yes and No correctly. After replacing the fixed number of spaces with a regular expression, everything worked correctly.  I can assume that this problem occurs not only on my localization.
> [MicroWin] Get-LocalizedYesNo does not work correctly for some localizations

- config/tweaks.json
- functions/private/MicroWin-Helper.ps1
- Change to capture unique value per machine, wildcard should suffice (untested)?
[Issue#1258](https://github.com/ChrisTitusTech/winutil/issues/1258)
- `dc2a4` is the hardcoded value in the current code
Example(s):
```powershell
{
"Name": "BcastDVRUserService_dc2a4",
"StartupType": "Manual",
"OriginalType": "Manual"
},
{
"Name": "BluetoothUserService_dc2a4",
"StartupType": "Manual",
"OriginalType": "Manual"
},
```
> Remove hardcoded GUID on services

- functions/private/Get-Oscdimg.ps1
- winutil.ps1
The old hash was for other exe, the hash for the new exe is replaced here.
> Fix wrong hash verification for oscdimg

- config/applications.json
- xaml/inputXML.xaml
The Winget package for Chromium was previously the one for Ungoogled-Chromium, I fixed it and added Ungoogled-Chromium as a separate package instead.
> Fix Winget package for Chromium and add Ungoogled-Chromium

- functions/private/MicroWin-Helper.ps1
- functions/public/Invoke-WPFMicrowin.ps1
- winutil.ps1
Adds a switch to `Remove-ProvisionedPackages` to determine whether we should remove Windows Security (GUI component, `Microsoft.SecHealthUI`).
Closes #1339
> Keep Windows Security

- winutil.ps1
- xaml/inputXML.xaml
In reference to:
https://github.com/ChrisTitusTech/winutil/issues/1338
Some users with screen sizes of different heights experience sections of tabs being cutoff with no way to access certain functions.
Simple fix to alleviate that issue by adding scrollbars to all tabs automatically based on application UI size.
> Added scrollbar to all tabs

- config/applications.json
- winutil.ps1
Cider has a new version that is not FOSS anymore and it's a paid program.
This is (or will soon be) deprecated.
> Remove Cider Music Player

- Compile.ps1
- config/preset.json
- config/tweaks.json
- functions/private/Get-WinUtilCheckBoxes.ps1
- functions/private/Invoke-MicroWin-Helper.ps1
- functions/private/Invoke-WinUtilTweaks.ps1
- functions/private/Show-CustomDialog.ps1
- functions/private/Update-WinUtilProgramWinget.ps1
- functions/public/Invoke-WPFButton.ps1
- functions/public/Invoke-WPFFeatureInstall.ps1
- functions/public/Invoke-WPFGetInstalled.ps1
- functions/public/Invoke-WPFImpex.ps1
- functions/public/Invoke-WPFInstall.ps1
- functions/public/Invoke-WPFInstallUpgrade.ps1
- functions/public/Invoke-WPFPresets.ps1
- functions/public/Invoke-WPFRunspace.ps1
- functions/public/Invoke-WPFShortcut.ps1
- functions/public/Invoke-WPFUnInstall.ps1
- functions/public/Invoke-WPFtweaksbutton.ps1
- functions/public/Invoke-WPFundoall.ps1
- scripts/main.ps1
- scripts/start.ps1
- winutil.ps1
- xaml/inputXML.xaml
- Fix version inefficiency the version is already stored in sync, no need to slow down loading by one extra replace.
- Created custom dialog and About message
- Create a menu with Import/Export values
- press on teh Settings cog in the right upper corner and save all the checkboxes
- then you can either load them or load and run automatically
- Made Import Export load across the whole app
- Optimized the way checkbox controls are looked up, it is 20% faster now
- Added a switch to load all the checkboxes from a config file
- example: ```.winutil.ps1 -Config "C:UsersasdfDesktop\111.json"```
- Added a switch to run all the actions from the config file by passing -Run switch
- example: ```.winutil.ps1 -Config "C:UsersasdfDesktop\111.json" -Run```
- This will run all the tweaks and install …
> Import/Export is now global, Settings menu added and many more improvements

- config/feature.json
- xaml/inputXML.xaml
- enable automatic windows registry backup and do schedule for it as well (disabled by default in Win10, Win11) this will help when doing last known Good Configuration thru the F8 startup menu.
- enable / disable legacy F8 startup recovery option.
- enable / disable web search suggestions in the windows search in task bar. (this will restart explorer process automatically to see the result)
> Add F8 Recovery Menu and Windows Reg Backup and others

- functions/private/Get-WinUtilToggleStatus.ps1
- functions/private/Invoke-WinUtilSnapFlyout.ps1
- functions/public/Invoke-WPFToggle.ps1
- xaml/inputXML.xaml
- Added new tweak **"Snap Assist Flyout"** that I think is useful for many people who do not like new feature that **MS** added when hover over **maximize** button.
- When **Disable/Enable** tweak, it will restart **explorer.exe** to take effect and set registry value **0/1** to **EnableSnapAssistFlyout**  
- <i>This will disable **ONLY** snap preview when hover **Maximize** button **NOT** snap preview when is **window** dragged to the edge of the screen.<i>
> Added new toggle tweak button

- functions/public/Invoke-WPFPresets.ps1
When selecting a preset it will also turn off all the sliders in the tweaks tab. Testing a fix for this issue.
> fix for bug with selecting presets and toggle switches

- config/applications.json
- Snappy Driver Installer Origin
Github source code deprecated. Replaced with SourceForge official source code site.
- Spacedrive File Manager
Changed winget, easier to identify.
"spacedrive.org" not working. Changed to official site.
**Recent Alpha ver 0.2.0 - crashing on install for Win10+ (not tested in "lower" win versions), may be better to remove overall or place on standby.**
- Xtreme Download Manager
Web Integration not working for chromium based browsers.
**Deprecated by Manifest V3, no official update release.**
> Fixes, Changes & Features Added (Broken links & Comments)

- xaml/inputXML.xaml
<Label Content="Snap Assist Flyout" Style="{StaticResource labelfortweaks}" ToolTip="**If enabled then File extensions (e.g., .txt, .jpg) are visible.**" \/>
---
-->
---
<Label Content="Snap Assist Flyout" Style="{StaticResource labelfortweaks}" ToolTip="**If enabled then Snap preview is disabled when maximize button is hovered.**" \/>
> fix tooltip label for Snap Assist Flyout tweak

- config/applications.json
GitHub CLI `gh` is the open source command line interface offered by GitHub alongside GitHub Desktop.
For more information and source code see: https://github.com/cli/cli. 
Installation Instructions taken from: https://github.com/cli/cli#windows
Official Site: https://cli.github.com
> Add GitHub CLI to applications

- config/applications.json
- added miniconda3,
- added temurin, 
- added presentmon (choco na),
- added pyenv-win (winget na)
- edited syncthingtray description
> added miniconda, temurin, presentmon and pyenv-win

- config/applications.json
This PR fixes Parsec's winget id in `applications.json`
`Parsec.parsec` -> `Parsec.Parsec`
> fix Parsec winget id

- config/applications.json
the neofetch-win package is from the [https://github.com/nepnep39/neofetch-win](https://github.com/nepnep39/neofetch-win) project and is separate to the neofetch used on linux
> change neofetch link to correct project

- config/tweaks.json
Fix OneDrive Remove Tweak not cleaning-up 'OneDrive' Folder under the 'localappdata' Environment Folder
Besides the 'OneDrive' Folder found in 'Microsoft' Folder in 'localappdata', there's Yet Another Cache Folder that OneDrive uses, which's found under the 'localappdata' Environment Folder, read the commit patches for exact details.
> Improved the OneDrive Tweak a bit

- functions/private/Invoke-MicroWin-Helper.ps1
MicroWin - Make the New Shortcut have 'Run as administrator' property on
The added lines of PowerShell Code was taken from public function 'Invoke-WPFShortcut.ps1' under the 'functions/public' Folder.
> Make MicroWin's New Desktop Shortcut have 'Run as administrator' property on

- config/applications.json
Added FireFox ESR, which was requested in #1705 Issue, and re-used the changes for Lightshot from #1626 PR.
Resolves: https://github.com/ChrisTitusTech/winutil/issues/1705
> Add 'FireFox ESR' and 'lightshot' Apps to 'application.json' File

- functions/private/Get-WinUtilWingetLatest.ps1
- functions/private/Get-WinUtilWingetPrerequisites.ps1
- functions/private/Install-WinUtilProgramWinget.ps1
- functions/private/Install-WinUtilWinget.ps1
Watched your recent Stream Archive on Titus Tech Talk and you thought out loud about the Winget install stuff. I figured... I've done that and ADHD'd my way to this solution. To get the functions to work, I had to separate the ps1, into 3 ps1 files. 
**Disclaimer:** While troubleshooting, I came across an error with the Install-WinUtilProgramWinget and patched it with a comment detailing the reason for my change, it's also documented here under "Fixes". 
I tested this on clean installs of Windows 10 and 11, and confirmed it working with the base winutil and these changes, in effect. 
**This is my first public _Pull Request_ so feel free to rail me in the next stream.** 
- Removed Get-LatestHash from Install-WinUtilWinget.ps1, replaced by Get-WinUtilWingetLatest.ps1.
- Added new Winget …
> Implement New Winget Install Method

- winutil.ps1
Fixed The Term "Get-WmiObject" is not recognized as the name of a cmdlet
$gpuinfo = Get-WmiObject Win32_VideoController which caused winutil to perform badly
> Fixed issue #1736 and #1749

- functions/private/Install-WinUtilChoco.ps1
- functions/private/Install-WinUtilWinget.ps1
- functions/private/Test-WinUtilPackageManager.ps1
- functions/public/Invoke-WPFGetInstalled.ps1
- functions/public/Invoke-WPFInstallUpgrade.ps1
I created this Pull Request to change the default behavior of Winget's installation method. This was so that by default it would install using the GitHub method unless failing—failing over to using Chocolatey. 
Also changed Test-WinUtilPackageManager to return more verbose responses, then implemented it's use in various Functions that were previously using `Get-Command`. This moves multiple uses of the same code to one location. Added Color to beautify the terminal output.
Split into two commits.
Tested in Windows 10 (22H2)
- Updated Test-WinUtilPackageManager to better handle the -Winget param and return a more verbose status.
- Moved many of the "is installed"/"is not installed" outputs to the Test-WinUtilPackageManager function.
- Changed Install-WinUtilWinget to use the GitHub install …
> Update of Test-WinUtilPackageManager and Install-WinUtilWinget

- functions/public/Invoke-WPFGetIso.ps1
- winutil.ps1
This PR adds checks to see if the available disk space is lower than a threshold specified by the ISO file chosen.
- If the disk space is lower than double the ISO size, the script will throw a warning
- If the disk space is lower than the ISO size, the script will throw an error and fail the operations
This should work fine and should close #1740
*P.S.: I may have finally figured out how to avoid the indentation issues!*
> Detect free space of installation drive and compare it with the ISO size and delete temporary MicroWin files from previous runs

- functions/private/Invoke-WinUtilTweaks.ps1
Added a new parameter that gives freedom of control on whether to disable this feature or not, and of course the simple feature in question.
The way it works is by Getting the service using its name, and see if the Startup Value of this service is equal to the default type that Windows comes with it, if not (The User has changed it in the past), then WinUtil won't change it by default (The KeepServiceStartup is true by default), this is a more desirable behaviour when compared to how it previously worked.
These changes were tested by the Author of this commit, Please read the commit patches for exact details on the changes.
Resolves #1726
> Add Simple Feature to keep the Service Startup upon Applying Service Tweaks, but not when Undoing it

- functions/private/Install-WinUtilWinget.ps1
- Sometimes, if Winget is installed under user-scope, the source isn't properly installed so that the Admin user can properly use Winget.
- This change installs the sources directly from the Winget CDN.
- Fixes #1771  
- https://github.com/microsoft/winget-cli/discussions/3258#discussioncomment-5951658
> Winget Sources fix

- config/tweaks.json
- functions/private/Get-WinUtilToggleStatus.ps1
- functions/private/Invoke-WinUtilTaskbarWidgets.ps1
- functions/public/Invoke-WPFToggle.ps1
A while back when I was watching one of your live stream records on youtube, You pointed out that Widgets found on Taskbar gets shown for whatever reason after applying tweaks, so I wondered if there's a way to disable/enable this feature, one or two google searches and found this [great blog post](https://www.top-password.com/blog/remove-widgets-on-windows-11-taskbar/) by top-password.com
After days of wanting to do it, I've found the free time to implement/understand how it all works, not knowing how to implement it was the hard part, noticed there isn't much on the documentation side for devs who want to contribute, may be something a more experienced person can help with this if they have the time to do so.. but nonetheless, any project can be understood with good old grep's recursive …
> Add New Toggle to Disable/Enable Widgets found in Taskbar

- scripts/main.ps1
> Fix Search Box Not Showing Apps/Tweaks Checkboxes When typing out Capital-Letters

- config/tweaks.json
In general, I've added two lines of code to get the explorer process using 'Get-Process', then passed the process object into 'Stop-Process', Windows will automatically restart explorer, so there's no need to run a new process for explorer.
Note: restarting explorer in the UndoScript might not be necessary, as it works just fine without it, that's according to the tests done by the author of this commit.
> Restart Explorer after Applying Classic Right-Click Advance Tweak

- config/tweaks.json
This is a tweak that allows you to right click on a program in the taskbar and end the task, instead of closing, normally found in development settings.
> Add end task via taskbar tweak

- config/tweaks.json
As I got suggested by @SkylerWallace on my previous PR #1827, the idea is to disable Second Out of Box Experience (SCOOBE) under the Disable Telemetry tweak. My reasoning is that this screen is a very annoying invitation to re-enable telemetry, and in my professional opinion a security risk. I know there's an option in Windows Settings to disable this, but in my opinion it's maliciously hard to reach (I didn't know about it's existence until now) and easy to forget while setting up a new computer, so adding it on this Tweak would be convenient.
Sources:
https://www.elevenforum.com/t/enable-or-disable-lets-finish-setting-up-your-device-in-windows-11.5205/#Two
https://www.tenforums.com/tutorials/137645-turn-off-get-even-more-out-windows-suggestions-windows-10-a.html#option2
> Add Disable SCOOBE in Disable Telemetry Tweak

- README.md
- config/applications.json
Resolves #1780 in 8d05769db3ef97c36a98e3db03dfe77b54cae99a commit
Resolves #1767 in 0c11905723677910ff343212deebacde9b623c2c commit
Other commits are to fulfill some of the Requested Programs in [Program Additions List](https://github.com/ChrisTitusTech/winutil/issues/1782).
> Added Requested Apps and Update Command Example in 'README.md' File

- config/applications.json
For whatever reason, Compiling using the 'Compile.ps1' Script when there's a Single Quote, in the description of an App for example, it'll try "escaping" it by adding another Single Quote, which's kind of weird.
Before there was an Apostrophe, and it'll Compile into Question Marks, probably because the Compile Script doesn't know what an Apostrophe is, or it can't escape it (or for another reason, didn't dig deeper into it), in the end I've made it neither an Apostrophe nor a Single Quote, just the sentence without contractions (Without shortening by combining words).
> A Temporary Fix to Compilation Program in 'Compile.ps1' Script

- functions/private/Install-WinUtilProgramWinget.ps1
- functions/private/Install-WinUtilWinget.ps1
- Changed how WinGet installs and uninstalls are handled, by utilizing `Install-WinGetPackage` and `Uninstall-WinGetPackage`.
I learned today that PS Modules utilizing WinGet are installed alongside WinGet as of a few years ago. With the changes to how Winget Updating is handled by my other PR #1829, this should be a better solution to handling installs going forward. In the cases I tested, checking Status was the best way to handle issues with a package installer not having machine scope capabilities. 
If anyone has any better ways to handle this, let me know. 
This should fix issues, like: #1805 #1756
> Update Winget Install and Uninstall / Add NuGet and Microsoft.Winget.Client Modules

- .github/workflows/close-old-issues.yaml
A Skill Issue moment, not gonna lie 😂
_Now_ this feature should work properly (This PR is a follow-up to https://github.com/ChrisTitusTech/winutil/pull/1801 PR)
> [!NOTE]
> As stated in https://github.com/ChrisTitusTech/winutil/pull/1801 PR, WinUtil Repo will need a new label for this, name of label should be the same as `labelKeepIssue` Const Variable in the Workflow's Script, if you want to change the Label Name, then make sure to change `labelKeepIssue` as well. Not Making a Label with said name, or Making these two Different **will render this feature useless**. Otherwise, it should work just fine 👍
> Fix Github Actions Auto Close Issues not leaving Issues Open

- Compile.ps1
- config/applications.json
- Fixes `Cannot convert value "XAML STRING HERE" to type "System.Xml.XmlDocument". Error: "An error occurred while parsing ENTRY-NAME. Line X, position Y."` Issue when running `winutil.ps1`, which's shown when some special characters are present in WinUtil's XAML Strings. So I've Handled these special character by simply replacing them in the `content` and `description` fields with (the places where it's most common/only found at the time of writing) with Escaped Ones, see commit https://github.com/ChrisTitusTech/winutil/commit/c2055c4efcde454b412a5377ea90ac51c0885482 for more details.
- reverted the changes of https://github.com/ChrisTitusTech/winutil/pull/1844 PR in commit https://github.com/ChrisTitusTech/winutil/commit/f918b2228015595fb8a92e7788c40f80c960316b
- ~Committed & Pushed a …
> Better JSON Parsing for Compile Script!!

- functions/private/Install-WinUtilProgramWinget.ps1
- functions/public/Invoke-WPFOOSU
- winutil.ps1
This is a special pull request to fix ALL program installs so we no longer have to worry about if it wants systemwide installs, user scope, or unelevated. It will automatically adjust on failure and get any of the programs installed.
> Fix ALL Program Installs

- config/applications.json
Satisfies some requests in #1782 Tracking issue list
> Several Additions to 'applications.json' File

- config/applications.json
I have noticed that nvm is available, but fnm is not. So, I have added fnm
> Added "Fast Node Manager" to the install section

- functions/public/Invoke-WPFShortcut.ps1
- Besides adding a few comments to make the Logic of this function slightly more clear (in commit https://github.com/ChrisTitusTech/winutil/commit/e2f07fa109848caf3f210f3a657a26ce0579d0e6)
- I also made the function "Lazier" by simply doing an Early Return when the User cancels the 'Save As' Operation, as we don't need to do the rest of code. (in commit https://github.com/ChrisTitusTech/winutil/commit/e7e41825d5b0843c7469ddb6045de1fa53817786)
This resolving the False Info outputted in the terminal whenever you cancel the Save As Operation ( it outputs to the Terminal `Shortcut for WinUtil has been saved to %USERPROFILE%\Desktop\WinUtil.lnk with 'Run as administrator' set to True`.. even though we canceled the operation :/ ), and this adds a small efficiency to the process.
> Simple improvement: make WinUtil's Shortcut Function Do Less (Lazier)

- config/tweaks.json
After the last PR I made I had a bit more time to spend creating Copilot removal.
Essentially it works in the following way:
1. It uninstalls some Copilot packages
2. Unpins Copilot from taskbar
3. Disables the ability to pin Copilot back to the taskbar
> Add option to remove Microsoft Copilot AI

- config/applications.json
Authy reached EOL in march 2024, no longer supporting desktop app
see:
https://help.twilio.com/articles/22771146070299-User-guide-End-of-Life-EOL-for-Twilio-Authy-Desktop-app
> Remove Authy (Reached EOL)

- config/applications.json
- config/tweaks.json
- Removes StartAllBack as of your request and because it apparently does not work in 24H2 anymore.
- Adds Netbird (https://netbird.io)
- Adds Tweak that sets the many Services from Adobe to manual
- That seems to work for me, didn't test it on multiple Machines because i dont want unnecessary shit on my devices
> Remove StartAllBack + Adobe Debloater Tweak + Add Netbird

- config/applications.json
The url link when clicking on `?` goes to the wrong repository, a trailing `f` character.
> Fix incorrect url for jellyfin-media-player

- functions/private/Get-WinUtilWingetLatest.ps1
Microsoft in its endless wisdom, created Invoke-Webrequest in such a way that the progress bar, which is shown during a download, drastically reduces the download speed that can be achieved. This is especially painful when downloading larger files (like winget ~200+ MB) 
The simplest workaround is, to disable the progress bar for the time of the download and print a message like "Downloading..." manually.
> Optimize winget download speed

- Compile.ps1
- functions/public/Invoke-WPFOOSU
Changed the compile script so that the OOSU Config files are Compiled right into winutil.ps1 and do not need to be downloaded afterward. 
This removes the need to have a static download link referencing the main branch of the repo.
The idea came from a discussion in #1921
> Compile OOSU Config into winutil.ps1

- functions/private/Install-WinUtilWinget.ps1
- functions/public/Invoke-WPFFixesWinget.ps1
- functions/public/Invoke-WPFGetIso.ps1
- scripts/main.ps1
This PR changes the behavior of the script to only install chocolatey if needed, and not as per default on the startup of winutil. 
Changed the main script to check/install if winutil is installed instead of choco.
Added checks in the places where choco is called to make sure that everything keeps working as expected.
> Only install choco if needed

- scripts/start.ps1
- Simplified the admin check by filtering the "WindowsIdentity" class for owner value and comparing against admin value
- Removed the need for an if admin check by moving its commands under the if not admin check.
- Added code comments
> Simplified Admin Check and Added Code Comments

- scripts/main.ps1
Condition is comparing $proc.Id with [System.IntPtr]::Zero. The Id property is an integer, representing the process ID, and it's not directly related to window handles. Instead, you should compare the MainWindowHandle property against [System.IntPtr]::Zero
> Main window handle

- config/applications.json
Added [SMPlayer](https://smplayer.info): free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats.
Request by https://github.com/ChrisTitusTech/winutil/issues/1782#issuecomment-2098024528.
> Add SMPlayer to `applications.json`

- README.md
- config/applications.json
- config/tweaks.json
- functions/private/Get-TabXaml.ps1
- functions/private/Get-WinUtilCheckBoxes.ps1
- functions/private/Get-WinUtilToggleStatus.ps1
- functions/private/Invoke-WinUtilSnapSuggestion.ps1
- functions/private/Invoke-WinUtilSnapWindow.ps1
- functions/public/Invoke-WPFToggle.ps1
- winutil.ps1
- xaml/inputApp.xaml
- xaml/inputTweaks.xaml
- xaml/inputXML.xaml
Disclaimer:
- You can run/test my fork using `irm mdiana.win/util | iex`
- Everything was tested on two devices running Win11 23H2
- It seems to work for me :)
Fixes:
- Fixed "WPFTweaksRestorePoint" to always run as first tweak, which it does at the time but only because it starts with "C" & the ordering of the tweaks is done alphabetically.
- Fixed Shell Names in "Right-Click Method" under "Usage" in README to accurate ones
Modifications:
- Moved Checkboxes a bit to the right so it looks more organized with the rest
- Redesigned Preferences
- Put Toggles to the left instead of the right to be more consistent in the design
- Removed "Enable" & "Disable" from the toggles because they define the action (which would be the other way around). 
but actually define the state. Adding another d …
> Adobe Network Blocking / Adobe Debloater / Tweak Fixes & more

- config/tweaks.json
This is to fix the confusion talked about in #1907 
* Removed "GameDVR_DXGIHonorFSEWindowsCompatible" modification from "Disable GameDVR" tweak
* Created advanced tweak "Disable fullscreen optimizations"
Disables fullscreen optimizations in all applications. (Which can cause problems with Color Management in Exclusive Fullscreen)
> Made disabling Fullscreen optimizations its own tweak

- config/applications.json
<div align="center">
<p><i>The App Entry not order correctly, and the fact the Install Function(s) can't pick the App Name due to the Typo Position affecting the Underlying Logic.</i></p>
</div>
Beside better/stricter PR review process, _even though in this particular case, the typo was caught waayyy back (approx. 2 weeks ago) in https://github.com/ChrisTitusTech/winutil/pull/1891 PR_, there should be Automatic Checks for these kind of issue, which it can be in the `Compile.ps1` Script, or as a Separate Unit Test all together.
This solution above should reduce the possibility of this ever happening again, because the Unit Test(s) will catch it as soon as possible.. _at least, that's in theory_.
> Fix Typo in the App Entry 'GlazeWM' in 'applications.json' File

- config/applications.json
NDI, or Network Device Interface, is developed by Newtek. It enables the encoding, transmission, and reception of high-quality, low latency, video and audio on your local network via IP.
You can turn computer desktops (via included screen capture apps) and even phones into video sources that can be brought into apps like OBS or vMix. Includes a plug-in for VLC that turns VLC into a video or audio playback source. You can even view and control many PTZ cameras, and tons of other features. Everything connects automatically over your local network.  
https://ndi.video/
> Update applications.json - Added NDI tools

- config/tweaks.json
- functions/public/Invoke-WPFTweakPS7.ps1
Reopen Pull Request for #1991 
Because I accidently delete the Branch on my Repo
Thanks for the @Marterich for the fixes of Powershell Core install
Using one button able to install Powershell 7 and set the default in Windows Terminal.
https://github.com/ChrisTitusTech/winutil/assets/62820836/2995670a-c48c-4b51-a9f7-a23c1b9df170
> Able to set the Default Terminal to Powershell 7 in Windows Terminal

- functions/private/Install-WinUtilProgramWinget.ps1
Fix return code handling : 
- If you had an application installed and clicked install/update again, winget would exit with return code "-1978335189" No applicable update found, which is != 0, and therefore the logic for the fallback installation methods would start.
Changed winget window management: 
- Modified the winget install to utilize the open powershell window rather than create new windows for each install. 
Personal opinion: I think the function Install-WinUtilProgramWinget is starting to get a bit out of hand in terms of repetition of code blocks, repetition of the same arguments for winget, and so on.  I think that we should rework the function (maybe after the next release when it's clear if the fallback works as expected) and maybe split it up into smaller logic blocks, or …
> Winget install return code handling & Window management

- config/applications.json
The winget does not work for vencord. The installer downloads and then fails. (#1515)
> Removed broken winget from applications.json

- functions/private/Get-TabXaml.ps1
- functions/private/Get-WPFObjectName.ps1
- scripts/main.ps1
Modified the display behavior of the Labels with the Category Description to be hidden on the application page if the category does not contain any applications (for example while using the search)
> Optimize Display Behaviour of Category Labels 

- .github/workflows/close-old-issues.yaml
This would allow this workflow to be more maintainable in the future, and will offload the responsibility of the core feature(s) to be maintained by the GitHub community over on [their repo](https://github.com/actions/stale).
@ChrisTitusTech if you want to make this workflow more customizable, for example, adding a Stale to Issues, to notify the Author(s) and participances about an Issue _**before**_ it get closed shortly after, then you can do so, please refer to [the README file over on actions/stale repo](https://github.com/actions/stale/blob/main/README.md).
Also, it support closing of PRs if you want to add this functionality.. even though I do see it that useful for a project like WinUtil, but hay, the choice is yours Chris.
> [!NOTE]
> There's a great example with explanation over …
> Simplify 'Close Old Issues' Workflow by using 'actions/stale' GitHub Action

- Compile.ps1
- scripts/main.ps1
- winutil.ps1
- Removes the forced install of winget on startup. Suppose a user clicks install on the applications page. In that case, winget will be installed anyways, but this removes the delay on bootup for users with a bad internet connection and only want to use winget for the tweaks or micro win. (Closes #2076, Closes #2068, Closes #2039, Closes #2022, Closes #2065) (Maybe it's possible to install winget in a separate Runspace but I haven't tested this)
- Disables the unnecessary Progress bar on bootup which is normally shown when "Get-ComputerInfo" is run. The user doesn't care how long this takes, because the command runs in a separate Runspace anyway. 
- Adds a -Run Toggle in the Compile script so when developing and constantly recompiling and testing, it's easier to compile and run with a …
> Remove force install of Winget + Small improvements

- config/tweaks.json
- winutil.ps1
Should Resolve: #2032
It should not change anything to remove the service from the Tweak.
The default value Windows Assigns the service is Manual anyway so for most people, this setting never changed anything, but in some cases (as in the above issue) the service seems to get set to Automatic by the OEM which would be overwritten by winutil and therefore break functionality for part of the Wwan components.
> Remove WwanSvc Service From Manual Services Tweak

- config/applications.json
Closes: #2066
Chocolatey Flagged this app as a Virus. The Package will be removed from winutil and (potentially) can later be readded if it turns out to be a False Positive
https://community.chocolatey.org/packages/FreeFileSync#virus
_Originally posted by @Marterich in https://github.com/ChrisTitusTech/winutil/issues/2066#issuecomment-2174075678_
> Removed Free File Sync because of Malware warning on choco repo

- xaml/inputXML.xaml
When I use WinUtil in dark mode I always get a small offcolored rectangle on the bottom right of the toolbox. I did following things to fix it:
- created rectangle, color it with backgroundcolor and place it at the blank space.
- added xName to Application ScrollViewer to get the state of it's scrollbars
- added style for rectangle that triggers it to show if both scrollbars are visible
Before:
After:
bc of the trigger the rectangle will not show if not needed so it won't brake anything else.
> Fix White space (bottom right of Application Tab)

- xaml/inputXML.xaml
Fixing Spelling of uninstall button:
- We uninstall the selected ones, we don't uninstall the selction.
> Spelling Fix: uninstall button

- scripts/main.ps1
Since I and other did not find a way to correctly change the Icon of the Taskbaritem, i added the icon as an overlay.
Preview:
Edit:
- Removed old commented-out code to set Taskbar Icon since it does not work.
> Add Overlay to Taskbaritem

- config/tweaks.json
Add Credit to Author of Hosts file from Adobe Networ Block in description.
- Giving Credit (if reasonable) is always a good thing
> Adobe Network Block Credit

- functions/private/Invoke-MicroWin-Helper.ps1
This PR provides a possible fix for AppX package removal, which many users reported fails for some apps with errors like "Removal failed. Please contact your software vendor"
Here's a link to a Stack Overflow post about a user facing this issue: https://stackoverflow.com/questions/70700451/remove-appxpackage-fails-with-error-0x80070002
Now, an application that fails at being removed will go to the `catch` block and continue the loop, effectively ignoring it.
Please make changes to this PR if it doesn't solve the issue. Also, with this new way of contributing things, I'm lost in the weeds, given that now we contribute to the main branch.
> Added Try-Catch block for AppX package removal

- config/applications.json
The program Ditto had a duplicate entry.
I removed:
```
"WPFInstallditto": {
"category": "Utilities",
"choco": "ditto",
"content": "Ditto",
"description": "Ditto is an extension to the standard windows clipboard.",
"link": "https://ditto-cp.sourceforge.io/",
"winget": "Ditto.Ditto"
},
```
In favor of:
```
"WPFInstallditto": {
"category": "Utilities",
"choco": "ditto",
"content": "Ditto (Clipboard Manager)",
"description": "Ditto is an extension to the Windows Clipboard. You copy something to the Clipboard and Ditto takes what you copied and stores it in a database to retrieve at a later time.",
"link": "https://github.com/sabrogden/Ditto",
"winget": "Ditto.Ditto"
},
```
Because I think that the title "Ditto (Clipboard Manager)" is more helpful than just "Ditto" and that it is more useful …
> remove duplicate of ditto

- config/preset.json
- config/tweaks.json
- winutil.ps1
Removes `HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent\DisableWindowsConsumerFeatures` from the big Telemetry Tweak and moves it into its own Tweak with a meaningful description of what it does.
This was done because it also inhibits the use of the Phone Link App which some people do use, so this provides a fairly easy way to selectively disable the tweak without needing to open an Issue or Coding/Windows Internals knowledge.  
Resolves: #2033
Resolves: #1670
> DisableConsumerFeatures Tweak

- config/applications.json
Hello, this is my first PR ever! I use WinUtil all the time and decided to fix this small error after watching your recent video about contributing to open source. Thanks for all the work you do an this awesome project :).
Very small and hardly noticable, but there actually is a Chocolatey package for Borderless Gaming called "borderlessgaming", not a big deal because from my understanding, Chocolatey packages are just fallback if the winget package is unreachable, and there is a working package there already, but hopefully this makes someone's life easier.
> Add a Chocolatey package for Borderless Gaming

- functions/public/Invoke-WPFUnInstall.ps1
Uninstallation Process has a popup that asks for programms to install. I fixed the spelling mistake.
> Fix: Uninstall Popup Spelling Mistake

- config/applications.json
Removed the following applications that I think are bloating the app list:
[WinDirStat](https://windirstat.net/) - WinDirStat is outdated. WizTree should be used instead
[BitComet](https://www.bitcomet.com) - BitComet is adware and has a history of unethical practices. [VirusTotal](https://www.virustotal.com/gui/file/7ccef9af5267c22a56bdbaf2f9109a02611bba461e0b0321bed42b5911163272), I don't know if these are false positives or not but there are so many better options
[BlueStacks](https://www.bluestacks.com/) - BlueStack 5's installation process forcibly install BlueStacks X and a crypto wallet alongside it
Additionally I have removed a duplicate entry of Ditto and changed the link on the entry remaining
> Purging applications

- config/applications.json
Satisfies a request made in Issue #1782 Tracking List.
- **Advanced Renamer** ([website](https://www.advancedrenamer.com/)): Advanced Renamer is a program for renaming multiple files and folders at once. By configuring renaming methods the names can be manipulated in various ways.
**License**: Proprietary
**Privacy Notice**: https://www.advancedrenamer.com/privacy
**Alternatives found in WinUtil**: PowerToys by Microsoft (Open Source) - has a tool called "PowerRenamer", Bulk Rename Utility (Proprietary).
- **Transmission** ([website](https://transmissionbt.com/) , [GitHub Repo](https://github.com/transmission/transmission)): Transmission is a cross-platform BitTorrent client that is open source, easy, powerful, and lean.
**License(s)**: GNU v2 & GNU v3 (among other Licenses), [here's a …
> Add 'Advanced Ranamer' & 'Transmission' Apps into 'applications.json' File

- .github/workflows/close-old-issues.yaml
- ~Remove un-necessary permissions in 'Close Old Issues' GitHub Workflow. ( commit 8fe062421d32ca67d22a716f69260588ee118541 )~
**Reverted in commit 6f838142a6674fcc9c4ad9acc402a4970840f496**
- Update 'Close Old Issues' GitHub Workflow to try and fix it, as there's currently a lot of inactive issues in the repo, and this commit adds quite a few comments which aids in future reviewing/understanding of this workflow file. ( commit 6e05426f125d6fc3f0ac94d749f7d583614c8281 )
> Fix 'close old issues' workflow

- config/applications.json
This will ensure no ambiguity would happen in the near future for this app entry.
This PR is a follow-up to https://github.com/ChrisTitusTech/winutil/pull/2159 PR
> Change WinGet ID for 'Fastfetch' to be 'Fastfetch-cli.Fastfetch' instead of 'fastfetch'

- windev.ps1
Initializes the windev.ps1 file at the root of the project.
It allows the contributors to change the loader in the future via a simple PR and removes the necessity of maintaining the file on the web server. 
**!!! Important !!!**
Please create an alias for https://christitus.com/windev and reference the following link: https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/windev.ps1
If a user runs the command: `irm https://christitus.com/windev | iex` the latest (pre) release will be started. 
Closes #2154
Closes #2060
Note:
Technically, it would also be possible to point the windev URL directly at the winutil.ps1 in the main branch since a pre-release is created for EVERY merge. I still think implementing this loader is the smartest way forward, in case the branch structure …
> Create Windev.ps1 loader

- config/applications.json
Just adding these two apps requested here: https://github.com/ChrisTitusTech/winutil/issues/1782#issuecomment-2195259964.
Note: WindowGrid has no winget package but has a Chocolatey package, not sure if I did this right, but feel free to fix it if I messed it up.
> Add 'voicemeeter potato' and 'windowgrid' to 'applications.json'

- .github/workflows/close-old-issues.yaml
Provides more 'head-room' for the 'stale' Actions to process all available Issues, as well as PRs.. because they're processed no matter what, and I can't force this action not to.. as far as I know.
- This will also remove the warning shown when this workflow runs shown in the Annotations Section.
[link to latest one at the time of writing](https://github.com/ChrisTitusTech/winutil/actions/runs/9719913811)
- The docs for `operations-pre-run` Field:
https://github.com/actions/stale#operations-per-run
> Pump up the value of 'operations-per-run' Field for 'Close Old Issues' Workflow

- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- windev.ps1
- Changes prerelease to include the prefix "pre" in the Tag to never overwrite/change main releases. (otherwise if you create a main release in the morning and merge a PR in the evening, the main Release will be marked as a pre-release again)
- Fix: Adds the Tag "Latest" to the Main Releases so that it works as expected
- change windev.ps1 to explicitly search for pre-releases (this is done because Github does not necessarily order the releases by last modified, but rather by the tag and name)
> Improvements/Fixes for the Release Actions

- KnownIssues.md
- README.md
At the time there are two Titles named Issues, to minimize confusion and properly use Known Issues for known Issues i moved that part to the file and referenced it directly under the launch command.
In addition i fixed the link in the command:
`[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/ChrisTitusTech/winutil/main/winutil.ps1')`
to use the link of the latest release instead of the winutil file in the repo folder:
`[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12;iex(New-Object Net.WebClient).DownloadString('https://github.com/ChrisTitusTech/winutil/releases/latest/download/winutil.ps1')`
I also moved an Issue that has to do with running the script …
> Move Launch Issues from ReadMe to Known Issues

- windev.ps1
Readded ability to redirect to latest release if it can't find a pre-release.
It was removed becaused we also removed the part specifically mentioning the pre-release, since it is added again because of an Issue I suggest also readding the redirect to the latest release
> Redirect dev to latest Full Release if can't find prerelease

- functions/public/Invoke-WPFMicrowin.ps1
This minor change helps distinguish the tasks of removing OS packages and AppX packages since these packages aren't the same. With this, in the case of a processing error, it may help developers to spot the exact issue.
> Allow for tasks to be distinguished

- config/applications.json
closes #2260
- Fix "nilesoftShel" to "nilesoftShell"
- Rename from "Shell (Expanded Context Menu)" to "Nilesoft Shell"
> Fix & Rename Nilesoft Shell

- functions/private/Install-WinUtilProgramWinget.ps1
because I couldn't find a way to change the variable `$x` on each iteration of the `ForEach` loop (and no it isn't because the x is capital in `$X++`.. already tried changing this, but to no avail ...)
So I've changed it to be a simple "C Like" For Loop, which has a variable `$i` initialized to the value of `0`, and on each iteration it'll increase by one (the `$i++` part).
If anyone can find a better solution then this.. then I welcome anyone to do so, and open a PR for it 👍
Resolves: https://github.com/ChrisTitusTech/winutil/issues/2233
> Change Main loop from 'ForEach' to 'For' inside 'Install-WinUtilProgramWinget' Private Function

- config/preset.json
- config/tweaks.json
As suggested in Issue #2248 , this will disable the Powershell 7 Telemetry by creating a new Environment Variable, tested it on Windows 11 23H2 (Build Number 22631.3737) and it works as expected.
The UndoScript simply deletes the Environment variable, [as explained in Microsoft Docs](https://learn.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4#set-environment-variables-with-setenvironmentvariable).
> Add new 'Disable Powershell 7 Telemetry' Tweak

- config/applications.json
Rework JDK packages with Corretto LTS ones
In the Java world, if a JDK release is non-LTS, then it is non-existent. Thus, non-LTS JDK releases, like 16, 18, and 19, create noise without value. Moreover, fragmentation between Oracle, Eclipse, and Temurin is not necessary. I added all the LTS releases through Amazon Corretto, which is known for its solid support with security updates and open source nature, including WinGet and Coco packages.
I have compiled and tested the program and the result is much cleaner.
Simplifies the workflow of installing JDK binaries through WinUtil.
- Resolves #1199
None.
> Rework JDK packages with Corretto LTS ones

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/close-discussion.yml
Discussions close on PR merge
Make it so discussions auto close on PR merge.
Can't test till merged.
Helps clear up discussions like how we can currently clear up issues.
No
> Discussions close on PR merge

- config/tweaks.json
- functions/public/Invoke-WPFShortcut.ps1
- functions/public/Invoke-WPFTweakPS7.ps1
- Use Powershell 7 for the winutil shortcut creation if available and fallback to PS5 if not
- Fix the Wording in the PS5-PS7 tweak
- Modify the tweak to handle systems without the Windows Terminal installed properly (eg. Win10) 
Tested on Win11 23H2 
Simulated devices without the Apps installed
Better performance because of the use of newer technology whenever possible
- Resolves #2308
> Optimized: Shortcut Creation and PS7 Tweak

- Compile.ps1
Fix how the Names of the JSON Objects are extracted and stored in a list during the compilation process
Tested on Win11 23H2 with Powershell 5 and Powershell 7
Should not be noticeable to the user
- Resolves #2321
> Fix Compile Errors on PowerShell 5

- functions/public/Invoke-WPFMicrowin.ps1
As stated in the title, remove Edge leftovers.
This pull request removes some leftovers of Microsoft Edge from the `WOW6432Node` key, which is only present on 64-bit images of Windows.
Testing concludes that the values and keys have been removed successfully.
No noticeable impact on performance
- Resolves #2202
The changes are strictly related to removing keys, so no documentation changes were required.
> Remove Edge leftovers from WOW6432Node

- config/applications.json
Adds Palemoon and closes old issues if not needed
Adds Palemoon browser to applications.json file and closes issues that have been fixed or issues that have been made that are not needed/necessary.
I have tested to make sure the program installs and shows in the UI.
Adds a program to Applications.json and closes old issues to clear them out.
- Resolves part of #1782 
No
Closes #2189
Closes #2206 
Closes #2232 
Closes #2243 
Closes #2249 
Closes #2097 
Closes #2318
> Adds Palemoon and closes old issues if not needed

- .github/ISSUE_TEMPLATE/bug_report.md
The change from Bold Text to a Header will make the Titles of each section pop more visually, which will _hoepfully_ make Bug Report Issues easier to review.
Tested these changes by committing to my main branch and see if it works as expected.
This won't impact the WinUtil Program directly, but will improve the Reporting of bugs a bit (indirect impact).
> Change the titles for each section from Bold Text to Header 2 in Bug Report Issue Template

- README.md
As described in the title, it'll make the `README.md` file shorter when rendered on GitHub.
Plus it'll follow the surrounding headers in its "linking-style".
> Make the 'Youtube Tutorial' Header be the link instead of the Youtube Thumbnail for it, Making the 'README.md' even shorter

- config/applications.json
This will fix WinUtil refusing to startup issue, giving an Xaml Syntax error.
At first I thought it's from your new Easter Egg.. _cogh_.. but after literally staring at the screen for 10 minute 😆 (just looking for syntax errors in your changes).. I was stuck to no avail ...
but at last, _and by using a similar technique I've used before in PR #1850_ (going through commit history, one commit at a time).. I've found the root cause of this issue (in PR #2316), which's the App Name Entry having a dash/minus symbol.. I'm just astounded on how it came to be, and how it passed the testing pipeline, but it was simple fix nonetheless.
- Resolves #2360
We should try avoiding this issue by updating the docs to tell people _**not to**_ add specific symbols in Field Names, and make the testing …
> Fix WinUtil Crashing on Startup - Xaml Error from Generated Applications List

- mkdocs.yml
-  New feature
- This is a Mkdocs material feature, so it's well tested, although on my system it wouldn't work particularly on Brave maybe something to do with brave shields idk :)
> [Wiki] Automatically enabling Dark/Light mode set by user's browser Preference 

- .github/workflows/issue-slash-commands.yaml
Add a GitHub Action that checks if any defined Contributors wrote "/close" in the comment body. If yes, close the Issue. 
This enables the specified Users to moderate the issue section and close inactive/old and already-answered Issues without having explicit maintainer permissions on the project
> Add /close command for the active contributors to close issues

- .github/workflows/close-discussion.yml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
remove ::set-output usage https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
remove `$version` as a environment variable as it's not used
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
removes warnings from GHA runs and removes not used variable from workflows
- Resolves #
[Any additional information that reviewers should be aware of.]
> Update workflows to remove `::set-output`

- .github/workflows/issue-slash-commands.yaml
Simple Optimization for the 'Close Issue on /close' Workflow ( made by @Marterich in PR #2380 ).
On my WinUtil Fork, there's a PR ([link to it](https://github.com/og-mrk/winutil/pull/14)) that didn't get closed by GitHub Actions after commenting on it ([link to the GitHub Actions run](https://github.com/og-mrk/winutil/actions/runs/10029358621)).
Also on my WinUtil Fork, you'll find an Issue Ticket ([link to it](https://github.com/og-mrk/winutil/issues/15)) that was closed after commenting on it with `/close` ([link to the GitHub Actions run](https://github.com/og-mrk/winutil/actions/runs/10029362195)).
This won't impact WinUtil Users, nor will it impact Contributors to this Project. But it'll optimize the Workflow a bit (shaving a few runtime minutes each month, depending on how the …
> Skip 'Close Issue on /close' Workflow if the comment was posted on a PR

- .github/workflows/close-discussion.yml
After trial & error, it now works as expected.
Supports all of [GitHub's Official Linking Keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), which're:
- Fix[es|ed]
- Close[s|d]
- Resolve[s|d]
This's done through Regex, look at the bash script in the workflow for more details...
> Fix 'Close Discussion on PR Merge' Workflow

- config/tweaks.json
Removed Enable/Show text on some preferences depending on how easy they are to understand.
Everyone knows that a filled out toggle is enabled, and if not it is still written in the description
tested, looks good
> Rename some Preferences

- functions/public/Invoke-WPFShortcut.ps1
Since noone looks at the command in the shortcut itself it would be the best Idea to make the command in there as compatible as possible. Since the one linked [here](https://christitustech.github.io/winutil/KnownIssues/#:~:text=If%20you%20are%20having%20TLS%201.2%20issues%2C%20or%20are%20having%20trouble%20resolving%20christitus.com/win%20then%20run%20with%20the%20following%20command%3A) is to long I've settled to changing the ctt url to the github url.
Worked
> Change shortcut command link to github release

- functions/private/Install-WinUtilProgramWinget.ps1
PR #2271 had a major flaw of installing some un-wanted apps from MS Store (as described in issue #2385), It was temporarily solved by reverting its changes in commit c90363181cf974c4342d5c3e01a58766d04cacf6.
This PR tries to solve the underlying logical error that PR #2271 had, which was trying to access out-of-bound memory (a common off-by-one error), where PowerShell would return `$null` (meaning the item this function has requested from `$ProgramsToInstall` Object Array is **an empty item**), which will make the Program ID (the input) an invalid value, causing un-expected behaviors from WinGet (The Package Manager), like installing the newest released app from MS Store.
After further testing (tried it with all sort of combinations, one app, multiple applications, some are installed …
> Re-apply PR #2271 & Fix For Loop in 'Install-WinUtilProgramWinget' Private Function

- config/tweaks.json
- functions/private/Get-WinUtilToggleStatus.ps1
- functions/private/Invoke-WinUtilDetailedBSoD.ps1
- functions/public/Invoke-WPFToggle.ps1
##Detailed BSoD
BSoD does not really give u much information, but with this tweak it will tell you what actually is wrong by using the BSoD that was used in Windows 7.
Testet it using the recommended method of crashing the system, using a reg key ateration + shortcut.
like [here](https://www.fortect.com/bsod/trigger-bsod-intentionally/)
Not much, a once in a lifetime change, understand if this does not get accepted
> Windows 7 BSoD Tweak

- config/tweaks.json
Windows lets microsoft store apps run in the background by default. Since Win11 u can't change that for all MS Store apps anymore throught the settings but still using the registry.
Worked as expected on multiple win11 instances, should also work on win10
> Disable Background Apps

- README.md
Describe steps to run script more precise and add some user-friendly notes in the documentation.
I believe there's a little bit of confusion for not tech-savvy people in the phrase "run with PowerShell or Windows Terminal" and it just makes no sense because opening Windows Terminal will get you to the actual PowerShell prompt.
And some people may be not sure of what branch of the script they better run, stable or dev, so I mentioned stable branch as a recommended.
More user-friendly experience for not tech-savvy people.
I'd like to make an another commit mentioning that you don't need the last iteration of PowerShell and you will be ok with just the default built-in "Windows PowerShell", but I'm not sure how to describe it the best and what's the oldest version possible which's able to …
> Make README.md more friendly

- config/applications.json
- winutil.ps1
Replace the Winget ID of Advanced Renamer. 
The old one works for the installation, but if you run winget list after advanced renamed is installed, this new ID is referenced. Therefore the app also wasn't shown under installed applications.
> Fix winget ID of Advanced Renamer

- .github/workflows/sponsors.yml
- winutil.ps1
Disables the Generate Sponsors Cronjob on Forks
At the moment, the workflow tries to run periodically on all up-to-date forks but fails because ${{ secrets.PAT }} is not configured. Depending on the Configuration of the User this results in failure E-Mails being sent to the user periodically. 
This change was directly taken from the PR #2402 by @wojsmol
No more Email and Notification Spam for Contributors
- Resolves #2468
The original PR also disabled the Compile and Close Issue Action. I don't see why this would be necessary because these actions run without a problem. Therefore I omitted them from this PR
> Disable the Generate Sponsors Cronjob on Forks

- edgeremoval.ps1
Enhanced Script for Comprehensive Removal of Microsoft Edge and Related Components
Type of Change
New feature
Bug fix
Documentation update
Refactoring
Hotfix
Security patch
UI/UX improvement
Description
This update provides an advanced, production-ready PowerShell script designed for a thorough removal of Microsoft Edge and its associated components. Key enhancements include:
Administrative Privilege Check: Ensures the script is executed with administrative rights.
Process Termination: Stops all Edge-related processes before removal.
Registry Cleanup: Removes specific registry entries related to Microsoft Edge.
AppX Package Removal: Uninstalls both provisioned and installed Edge AppX packages.
Shortcut Cleanup: Deletes shortcuts related to Edge from common locations.
Policy Configuration: …
> Pull Request

- functions/public/Invoke-WPFShortcut.ps1
- using vars that actually exist instead of imaginary ones.
- remove empty row at the start of the file
tested, did not work before, works now
- Resolves #2487
- Resolves #2510
- Resolves #2520
> fix shortcut creation

- functions/private/Show-CustomDialog.ps1
Dialogbox ("about" window) uses a custom theme and not the one the winutil gui uses, meaning light mode is not supported.
I changed it to use the existing theme, meaning it looks more like the gui and themes right in light mode.
Before:
After:
> fix dialogbox theme

- CONTRIBUTING.md
Due to short sighting on my end, I haven't notified @MyDrift-user in his PR #2481 that `docs/contribute.md` file has been updated in PR #2472, meaning the Out Dated version of `docs/contribute.md` file was copy-pasted into `CONTRIBUTING.md` file, which "reverted" changes made in PR #2472.
Built & Deployed these changes from my Fork (specifically this PR Branch), and it works without a problem.
Link to docs preview: https://og-mrk.github.io/winutil/contribute/
> [!NOTE]
> The build & deploy of github pages generates several warnings, I'll make a PR soon addressing this, but the changes introduced in this PR does not produce any extra errors or errors related to the changes.
> Re-Apply PR #2472 but for 'CONTRIBUTING.md' File

- functions/private/Get-WinUtilToggleStatus.ps1
- functions/private/Invoke-WinUtilDetailedBSoD.ps1
- Did not notice the issue because the key already existed on my machine, if the key does not yet exist it still sais it is enabled even tho it is not.
- Added disable emoticon (smily)
worked (tested correctly this time)
> Fix BSoD Tweak

- functions/public/Invoke-WPFMicrowin.ps1
Stable Edge Removal - MicroWin
Undoes the official way of integrating Edge into ISOs
- Doesn't break anything. If you install Edge later that's on you :P | use winutil tweaks in that case ;)
- Of Course it's so much better from doing inside the box.
- From the same author `Techie Jack` user who supplied the inbox removal fix :)
> MicroWin: Stable Edge Removal

- config/tweaks.json
- functions/private/Uninstall-WinUtilEdgeBrowser.ps1
- added working logic to reinstall MS Edge
- added logic to remove more reg keys on removal
- with those two reg removals edge does not give the big annoying welcome back screen but a "better" (still annoying) popup. It also offers a more clean uninstallation.
- fixed "open with" context menu having broken edge option bc MS Edge can't make a working uninstaller.
changes were tested on vm, run & undo work without sys/ep restart needed
> Edge removal improvements

- functions/private/Invoke-WinUtilMicroWin-Helper.ps1
(Same as title, but with MicroWin prepended to avoid confusion with other PRs)
This PR reinstates error handling for the AppX package removal function, which had been removed during the live stream on 13 August
AppX package removal still works
Reliability improvements
No issue. That's why I made this change - to prevent such issues from being reported
No documentation changes
> [MicroWin] Add try-catch block for AppX packages

- functions/private/Invoke-WinUtilMicroWin-Helper.ps1
(Same as title)
This PR fixes networking issues of MicroWin in VMware hypervisors. This involved excluding all Ethernet and Wi-Fi Features on Demand (FoDs) from package removal.
Testing was performed against a Windows 11 23H2 image and concluded with no issues
Network compatibility in VMware hypervisors
None AFAIK
No documentation changes were required
> [MicroWin] Fixed VMware network driver issues

- xaml/inputXML.xaml
Provide a direct link to the Windows 11 ISO download page
Removed the full link text to the Windows 11 ISO download site on the MicroWin tab and replaced it by making `Download` a direct link.
Tested by running `Compil;e.ps1 -run` and verifying clicking the link navigates to `https://www.microsoft.com/software-download/windows11`.
Adds convenience of a click over having to reference the text to enter the URL correctly (copy was not supported in the via text).
- Resolves #2573 
N/A
> Make "Download" a Link to Download the Latest Windows 11 ISO

- functions/public/Invoke-WPFMicrowin.ps1
(Same as title)
This PR removes the Test-Path condition, which is the culprit for ISOs being double their initial size by including both the unmodified and modified install.wim files.
For example, when I implemented registry cmdlets for DISMTools, it took an insanely huge amount of attempts to unlock the registry, so I replaced them with REG commands.
[Link to DT commit](https://github.com/CodingWonders/DISMTools/pull/140/commits/02d5d2e4132df48982a0d7b7c1e4c36fec660949)
**In short:** *Using registry cmdlets for offline images holds "System" process file locks for an uncertain amount of time until they are released, at which point unmounting has failed. Forcing a manual release of the lock will crash the system.*
One reason to rant about PowerShell, I guess.
It should finish successfully …
> [MicroWin] Remove test-path for issue fix

- config/themes.json
never use light mode, but for testing or on new systems I have to deal with it. I wonder why the background of the label is a tiny bit darker than the rest of the utility.
Did just catch it again and don't have any PR or stashed changes in that regard, therefore the individual PR.
<details>
<summary>old preview (attention, you may get blinded)</summary>
<br>
</details>
> Fix Label in white theme

- scripts/main.ps1
- Changing the order of operation in `main.ps1` script, where it'll check if XAML parsing was successful or not, before continuing on with UI Dynamic Generation. ( commit 32877fe200dbc2e08866a8a7e28e510444459518 )
- Use `Write-Host` instead of `Write-Warning` or even `Write-Error` because it can be ignored sometimes because of Runspaces and older ps shell environments (e.g. PowerShell 5). ( commit 0c4c4835dfa9d8841f0e6c8a7aac40db1e1bee2c )
tested the changes, and everything works as intended.
It'll fail fast/gracefully upon unsuccessful parsing of XAML, which'll speedup development a bit (not that much, but it can add up overtime), beside that it won't effect End Users.
> Small patches for `main.ps1` script

- config/applications.json
Removed the following projects:
- [ATLauncher](https://github.com/ATLauncher/ATLauncher) (600 Stars)
- [chromium](https://github.com/Hibbiki/chromium-win64) (400 Stars)
- [Windows Error Code Lookup](https://github.com/HenryPP/ErrorLookup) (200 Stars)
> Removed small projects from applications.json

- .github/PULL_REQUEST_TEMPLATE.md
Update PULL_REQUEST_TEMPLATE.md to link the contribute page
Update PULL_REQUEST_TEMPLATE.md to link the contribute page
None required
High as it makes sure all PR's are done correctly.
Nope
> Update PULL_REQUEST_TEMPLATE.md to link the contribute page

- config/tweaks.json
- Resolves Issue mentioned in Community Discord Server
> [OneDrive Removal fix] Leftover autostart key

- functions/public/Invoke-WPFImpex.ps1
- xaml/inputXML.xaml
- copy execution command to clipboard on export
- add tooltips to import & export menu items
- command is correctly escaped
- execution of just copied command works
- tooltips show
- People do not need to search for how to execute with the config in the docs, instead tet the command copied to the clipboard. To help people notice it i added tooltips to the import/export items-
> [Export Config] Copy command to clipboard

- functions/private/Invoke-WinUtilMicroWin-Helper.ps1
This PR adds error message information for catch blocks
Messages should be displayed in the event of an error
UX improvements
- Resolves all "issues" related to some packages that couldn't be removed
No documentation changes were required
> [MicroWin] Add error details and messages

- Compile.ps1
- config/themes.json
- scripts/main.ps1
- scripts/start.ps1
- windev.ps1
- xaml/inputXML.xaml
- Add auto size handling of window, but with a max size cap, that will be removed once the window is shown so the user can resize the window as wished. Window should on run never be to big for the screen again.
- change fontsize back to something lower to display content of winutil correctly, it was only changed bc og-mrk's branch was a bit older, meaning it had older values.
- Added Custom Margin for Microwin Checkboxes because their label cuts off if used withnormal margin.
- fixed layouting of fixed tweaks buttons to not cut off in the center and truly work on a mobile resolution
- add args param for compile script, which passes args to winutil
- improve run action in compile script
- move logs to after admin elevation
- fix left nav side being to big and cutting stuff off:
- closes …
> Fixes, improvements + Auto Window handling

- functions/public/Invoke-WPFImpex.ps1
Fix the configuration file import feature in the Invoke-WPFImpex function
This PR addresses an issue with the `Invoke-WPFImpex` function in `winutil.ps1`.
Recent changes to `Invoke-WPFImpex` require explicit string conversion for the `$flattenedJson` parameter.
The conversion was previously handled implicitly, but it now needs to be explicitly converted to ensure correct processing.
* Validated that the `$flattenedJson` parameter is now correctly processed as a string.
* Confirmed that configuration imports are successful with the updated function.
* Ensures that the `$flattenedJson` parameter is handled correctly as a string, preventing errors during configuration imports.
* Fixes #2657 
* None.
> Fix the configuration file import feature in the Invoke-WPFImpex function

- functions/public/Invoke-WPFUltimatePerformance.ps1
The issue appears to be related to the Windows language. I've noticed that the Ultimate Power Plan doesn't activate automatically because its name varies across different Windows languages.
I've created a small script that may help. It retrieves the GUID we just created, applies it, and changes the name and description simultaneously.
> Ultimate Performance via GUID rather than name

- scripts/main.ps1
Simplify WinUtil Directory Creation in 'main.ps1' script by using C# 'CreateDirectory' Method which checks and creates the provided Directory Path
> Simplify WinUtil Directory Creation in 'main.ps1' script

- functions/private/Invoke-WinUtilMicroWin-Helper.ps1
This PR excludes features that are already disabled in the image. It's nothing but a timesaver, especially for less powerful systems:
**EDIT:** Some (raw) benchmarks of the latest version and the one with this change:
- Latest Version: 51:17.55
- This PR: 39:07.56
**The benchmarks were performed on a dual-core system, with a couple of applications running. The time taken was measured manually. These values are subject to change depending on your hardware or software configuration.**
Testing was performed on a Windows 11 23H2 image and concluded with no issues. No differences were present across the current method and this one after grabbing the feature listings. Below are the actual differences of both reports:
- `experimental_features_report.md` contains feature listings of a Windows …
> [MicroWin] Don't disable already disabled features

- Compile.ps1
I am having the issue on some machines (where I sadly have to use onedrive) where onedrive process blocks the compile script from writing into winutil.ps1. But that happens at the end of the script meaning I am waiting for the compile to end just for it to error out on me after generating everything..
- remove winutil.ps1 if it is readonly (also works if another process is using it) to minimize failed compilations.
- worked for me now
> [fix compile] winutil used by another process

- .github/PULL_REQUEST_TEMPLATE.md
Removes "Pull Request" and "Title" as both of them are redundant & the title is already specified when you make a pull request + their is no reason to have "Pull Request" at the top of the template IMO.
Duplicate of [#277](https://github.com/ChrisTitusTech/linutil/pull/277)
Makes the template easier to work with when making a PR
> Remove redundant options in the template

- config/applications.json
Correct for winget Google.GoogleDrive
Winget install Google.Drive is incorrect, it should be Google.GoogleDrive
- Resolves #2702
> Correct for winget Google.GoogleDrive

- scripts/main.ps1
Fixed the following error by casting the content to string:
InvalidOperation at line 14824 
if ($CheckBox.Value.Content.ToLower().Contains($textToSearch)
Error: Method invocation failed because [System.Windows.Controls.TextBlock] does not contain a method named 'ToLower'.
Tested against the same input given to the release version on powershell version 7.4.5
Fixes an error displayed in the powershell
- Resolves #
> fix "ToLower" method invocation failure

- functions/private/Invoke-WinUtilMicroWin-Helper.ps1
This PR excludes Snipping Tool (Snip & Sketch on Windows 10) from AppX package listings to fix issues when pressing `Win + Shift + S` or to launch that app on command. Yes, even though there's ShareX for this (which is something I use as my main screenshot tool), some end users want a more "first-party" approach to making screenshots
Testing concluded with no issues
Restored missing functionality.
- Resolves #2736
No documentation changes are required
> [MicroWin] Exclude Snip & Sketch from AppX removal

- functions/private/Invoke-WinUtilMicroWin-Helper.ps1
This PR excludes the Search Engine package from feature listings. This fixes issues people were experiencing where the Indexing Options control panel applet was not present.
Even though Windows Search is crap, it's no longer that crippled on MicroWin.
Testing was performed on a Windows 11 23H2 image and concluded with no issues. ISO file sizes are the same.
Less broken functionality out of the box
- Resolves #2602
No documentation changes were required. No UI changes were required either, so it should not cause any merge conflicts with the "mega-PR" (#2693)
> [MicroWin] Exclude Search Engine Package

- functions/private/Invoke-WinUtilDarkMode.ps1
- functions/private/Invoke-WinUtilExplorerRefresh.ps1
Instead of restarting explorer, we could "refresh" it. For example when changing settings in the settings app it does not restart the explorer process, but still works fine. I am trying to recreate that.
- Added Explorer Refresh to Dark mode toggle
- This method does not work for heavyer stuff like window snapping, but I am passively searching for an alternative that works for everything (or atleast more)
- test worked fine
- reopening of #2616
> EP refresh

- functions/public/Invoke-WPFUltimatePerformance.ps1
Changes made:
- Modified the script to directly target the "ChrisTitus - Ultimate Power Plan" instead of using the general Ultimate Performance GUID for checking and deleting.
- Updated the code to use the specific GUID (381b4222-f694-41f0-9685-ff5bb260df2e) for the Balanced power plan, ensuring compatibility across different Windows languages.
- This change eliminates dependency on the localized name of the Balanced plan, making the script more robust in diverse language environments.
> Fix Ultimate Performance power plan deactivation

- scripts/main.ps1
Fixes a Typo in two variables. So that the settings button does work again
- Resolves #2778
> Fix Settings Variable Typo

- functions/private/Invoke-WinUtilDarkMode.ps1
- scripts/main.ps1
Listen to windows theme change events so that if a user changes from dark to light mode in the windows settings and also has the winutil theme set to auto, it updates instantly. 
Also update the Theme automatically if the setting is auto and the user activates the tweak to set windows to dark mode
> Reactively follow windows theme

- functions/public/Invoke-WPFUnInstall.ps1
Refactor: functions/public/Invoke-WPFUnInstall.ps1
- Simplify code and make it shorter
- Remove unnecessary null assignments
Not needed
Make code shorter and easier to read
- Resolves #
> refac(invoke-wpfuninstall.ps1): remove null assignments and simplify taskbaritem invocation

- config/tweaks.json
- restore point script includes elevation handling logic, not needed anymore due to winutil running as admin anyways
> Remove elevation from RestorePoint

- config/dns.json
- config/tweaks.json
Added dns0.eu, a European public DNS service.
https://www.dns0.eu/
- Successfully compiled using Compile.ps1 without issues.
- Ran winutil.ps1 and was able to select and change the DNS settings.
- Verified the settings in Windows.
- Tested on Windows 11 IoT Enterprise LTSC 24H2.
- Additional DNS Options: This change adds more flexibility for users by providing an additional public DNS service.
- Regional Benefits: Specifically beneficial for users in European regions, offering a geographically closer DNS service.
> Add dns0.eu

- tools/Invoke-Preprocessing.ps1
This PR should fix issue #2795 reported by @CodingWonders
Compiled WinUtil successfully in both PowerShell 5 & 7, and the main issue of `.git` getting corrupted by the preprocessor shouldn't happen again.
This won't impact End-Users, but the Developers who work on WinUtil (to be specific, devs who work in PowerShell 5 environment, which we're currently supporting with PowerShell 7).
- Resolves #2795
This was reported first by @CodingWonders on WinUtil Community Discord, so thanks again for notifying me (and others) about this issue 😄.
Also, I do realize that the preprocessor is very slow at the moment ( considering it doesn't do that complex of a task :/ ), will try to optimize / make it feature complete in the future, but for the time being.. my bad for wasting your time in compile times …
> Fix Excluding Logic for Preprocessor

- functions/public/Invoke-WPFImpex.ps1
- rework impex
- add link logic for importing config via param
- import link & path via param
- import & export via gui
> [IMPEX] add link support

- config/tweaks.json
Removed ms-edge polices which were causing "unknown policy" errors.
- Successfully compiled using Compile.ps1 without issues.
- Ran winutil.ps1 and was able to select and execute the tweak "Debloat Edge".
- Verified the settings in ms-edge (edge://policy/).
- Tested on ms-edge 129 on Windows 11 IoT Enterprise LTSC 24H2 (x64).
- Removed EdgeEnhanceImagesEnabled policy.
- Removed EdgeFollowEnabled policy.
> Fix: Resolve ms-edge policy errors by removing invalid policies

- config/tweaks.json
There are two identical tweaks for Edge Debloat (ConfigureDoNotTrack)
> Remove duplicate Edge Debloat tweak

- functions/private/Set-WinUtilRegistry.ps1
Adds the option to specify "<RemoveEntry>" as a Registry Value in the tweaks.json registry definition. 
When this is provided, the value will be fully removed instead of simply being set to a specific value.
Tested this on a demo Tweak and it seemed to work. 
This should not affect anything except when the Registry value is explicitly set to <RemoveEntry>
- Resolves #2821
@MyDrift-user I have no clue where to put this in the documentation. Maybe you can give me a hint on where to mention this "feature"
> Add logic to remove Registry Keys via Tweaks

- Compile.ps1
**NOTE: I recommend going through my commits to see the changes I made over time, to better understand why I coded things the way I did.**
Change Compile.ps1 to use here-strings with JSON.
This modifies the Compile.ps1 script's handling of JSON to use here-strings and `-Raw`, similar to what we do with Xaml. This allows us to forego the replace when we `ConvertTo-Json -Depth 3`.
There are a couple formatting to CamelCasing changes for consistency, as well. 
Tested the Compile in pwsh and powershell (pulled in changes from @og-mrk for Pre-processing for testing in PS5.)
> Use here-strings for JSON in Compile.ps1

- config/feature.json
Stray comma at the end of line 324, causing compiling issue in Powershell 5.
Since JSON handling is different between Powershell 5 and Powershell 7. You only notice the error during Compiling on Powershell 5.
Debugged and tested compile in Powershell 5 and 7.
Fixes #2864
> Hotfix feature.json

- config/tweaks.json
- docs/dev/tweaks/Essential-Tweaks/DisableRecall.md
Adds a new option to disable Recall using DISM and Reg Key
Added reg key to disable AI Data Analysis which turns off the snapshot feature of Recall in Registry and used DISM to disable the Recall feature as shown in Chris's video "Microsoft Recall Update".
Compiled and tested on Win11 24H2. Both Disable and Undo works verified using the command DISM /Online /Get-FeatureInfo /FeatureName:Recall
Just disables Recall.
Does not apply to older versions of Win11 or Win10
Added a new doc file to Essential-Tweaks DisableRecall.md
> Disable Recall

- functions/private/Invoke-WinUtilMicroWin-Helper.ps1
- functions/public/Invoke-WPFMicrowin.ps1
This PR removes the Recall exclusion and adds the **true** fix for #2697. Thanks to @witherornot and @thecatontheceiling for spotting this problem, and thanks to Microsoft for not testing Jack.
Testing has concluded with no issues
Clarify that it's a Windows bug. This should not have any impact on end-users.
- Resolves something external from GitHub - any misinformation caused by Recall being a "dependency"
Please test this for any issues.
> [MicroWin] Fix Recall "Dependency" Misinformation

- functions/private/Invoke-WinUtilMicroWin-Helper.ps1
This PR removes the WinUtil shortcut for MicroWin images due to the same reasons that affected the shortcut that could be created on demand - false positives.
This PR only removes the shortcut. No testing is required
Less support overhead for false positives
- Resolves all issues related to the shortcut
No documentation changes required.
> [MicroWin] Remove WinUtil shortcut on first logon

- config/tweaks.json
- functions/private/Set-WinUtilRegistry.ps1
- removes policies set by tweaks in winutil instead of setting them to diabled to remove "managed by organisation"
- works
- As to my knowledge, any policy reg entry can be deleted and if it is really needed or even forced it will just regenerate itself. So that should make no Issues. I did not find any issues either.
> Remove Policies in tweaks.json

- config/feature.json
- docs/dev/features/PowerShell-Profile/PSProfileInstall.md
- docs/dev/features/PowerShell-Profile/PSProfileUninstall.md
- functions/private/Invoke-WinUtilInstallPSProfile.ps1
- functions/private/Invoke-WinUtilUninstallPSProfile.ps1
- functions/public/Invoke-WPFButton.ps1
Implements the ability to uninstall the CTT PowerShell Profile and all its related dependencies.
I have tested the profile uninstallation functionality by running it in the following test scenarios:
- Baseline: Installing the CTT PowerShell Profile
- Test 1: Uninstallation of OhMyPosh dependency: [✅] Successful
- Test 2: Uninstallation of Nerd Fonts dependency: [❓] Conditional
- Additional Context: See `Notes for Test 2` in `Additional Information`.
- Test 3: Uninstallation of Terminal-Icons dependency: [✅] Successful
- Test 4: Uninstallation of Zoxide dependency: [✅] Successful
- Test 5: Skipping uninstallation of in-use dependencies: [✅] Successful
- Test 6: Uninstallation of CTT PowerShell Profile: [✅] Successful
- Covered by `## Description`, `## Testing`, and `## Additional …
> Remake PR: Uninstall CTT PowerShell Profile

- functions/private/Install-WinUtilProgramChoco.ps1
A simple change to Verbs to be in the list of Approved Verbs as expected by the Powershell coding standards. In powershell/pwsh run Get-Verb, to generate a list.
Check-UpgradeNeeded -> Test-UpgradeNeeded
Run-ChocoCommand -> Invoke-ChocoCommand
Compiled and Tested Installing and Uninstall with _Prefer Chocolatey_ selected.
> Use Approved Verbs in Install-WinUtilProgramChoco.ps1

- functions/microwin/Invoke-Microwin.ps1
Type of Change
Minor update (Console output addition)
Description
This PR adds a Write-Host statement to display the Windows Image version in the console. The change outputs the retrieved image version ($imgVersion) to provide visibility into the version details directly within the script execution output.
Example output:
The Windows Image Build Version is: [version number]
This modification is particularly useful for users who need to confirm the version of the Windows Image being processed.
Testing
Testing involved running the script to ensure that the Write-Host statement correctly displays the image version without causing any errors or affecting existing functionality.
Impact
This change has no impact on performance, dependencies, or behavior beyond adding a simple console output. It …
> Displays build version of input ISO

- Compile.ps1
Commit Summery:
- 974c46c Save WinUtil's json strings with DOS-Style Newline Character (CRLF) instead of Unix-Style Newline Character (LF)
Originated from PR https://github.com/ChrisTitusTech/winutil/pull/2816 by @ruxunderscore
- 5641623 Exit Early when facing Syntax Errors, Solves a problem when passing '-Run' Argument with 'Compile.ps1' Script - Use 'Out-Null' to follow common project conventions
Tested these changes when:
1. Compiling without providing any extra arguments (`Compile.ps1`)
2. Compiling with providing `-Run` Argument (`Compile.ps1 -Run`)
3. Compiling with providing `-Run -Arguments "-Debug"` (`Compile.ps1 -Run -Arguments "-Debug"`)
4. Done the previous cases when _**no syntax errors**_ are present and when there's _**syntax errors**_ in WinUtil's code base.
All previous …
> Simples fixes to 'Compile.ps1' Script

- functions/public/Invoke-WPFTab.ps1
Simple changes to `Invoke-WPFTab` Public Function, please look into the commit history/actual changes to learn more about these changes.
Commit Summery:
- f98d3be Improve 'Invoke-WPFTab' Parameter by specifying its type (as expected by the function) and make it Mandatory
- c0e8a14 Simple performance increases in 'Invoke-WPFTab' function - Use where method instead of piping the result into Where-Object
- 85d8db1 Remove commented-out code in 'Invoke-WPFTab' function
Switching between tabs works using the GUI as well as using the Shortcuts (`Alt` + `I | T | C | U | M`)
Not much of an impact, other then shaving a few milliseconds (at least in theory, didn't benchmark these changes to see if there's a noticeable difference).
> Simple changes to 'Invoke-WPFTab' Public Function

- functions/private/Set-WinUtilRegistry.ps1
I noticed WPFToggleTaskbarWidgets was giving a very generic issue 
Enabling Taskbar Widgets
Set-ItemProperty:
Line |
3764 |          Set-ItemProperty -Path $Path -Name TaskbarDa -Value $value
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Attempted to perform an unauthorized operation.
Now it will give 
Set HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarDa to 0
WARNING: Attempted to perform an unauthorized operation.
I have not done a tone of troubleshooting on my end on why I am unable to update that value in the registry (even manually)
> Add exception catch for Unauthorized Access

- functions/public/Invoke-WPFButton.ps1
- functions/public/Invoke-WPFSSHServer.ps1
Moved the OpenSSH installer to a runspace so the UI doesn't lock up
Compiled and tested with pwsh and powershell.exe
UI no longer locks up when installing OpenSSH
> Move Installer for OpenSSH to a runspace

- config/tweaks.json
- functions/private/Get-WinUtilToggleStatus.ps1
- Removes recommendation setting entirely from Start Menu (pinned list even gets longer and not cut)
- Tested on:
- Win11 23H2
- Win11 22H2
- Win10 21H2
- Resolves #2215
- Resolves #2037
- I am Enbling `iseducationenvironment` for this to work
https://learn.microsoft.com/en-us/windows/client-management/mdm/policy-csp-education#iseducationenvironment
> [FEAT] Remove Start Menu Recommendations / Fix GetToggle Logic

- .github/workflows/pre-release.yaml
Add a timestamp signature to the final artifact in order to still have a vaild signature even when the code signing certificate is already expired.
I have done an offline test with a local selfsigned codesign certificate in order to verify that this actually works with powershell scripts.
The final released powershell script carries a valid code signature even after the certificate with which it was signed is already expired.
- Resolves -
> Add timestamp server to code signature

- config/tweaks.json
- functions/private/Set-WinUtilRegistry.ps1
This is a small fix for the Recall tweak so that DISM no longer locks up the entire process due to input that is silently being asked.
Now, the user will be told to restart their computer.
It's a simple fix that disables the output and ignores a restart.
Bugs fixed - this is my first PR for the tweaks and not for MicroWin.
- Resolves #3120
No documentation changes are required.
> [Tweaks] Disable output for DISM for the Recall tweak

- config/applications.json
- docs/CONTRIBUTING.md
- docs/KnownIssues.md
- docs/index.md
- docs/userguide.md
- functions/public/Invoke-WPFImpex.ps1
> Use HTTPS instead of HTTP for URLs where supported.

- functions/microwin/Microwin-RemovePackages.ps1
Fixes a silly divide-by-zero error when attempting to remove packages with the fallback method.
Now it makes reference to the correct list. Additionally, testing from the issue creator has concluded successfully, making this PR a success.
Less buggy behavior
- Resolves #3170
No documentation changes required
> [MicroWin] Fixed divide by zero error for fallback

- config/applications.json
so fixed uniget id in winget as it changed to MartiCliment.UniGetUI as stated in #3162
tested it and it installed 
- Resolves #3162
> Fixed UniGetUI winget id

- functions/private/Install-WinUtilWinget.ps1
- functions/private/Test-WinUtilPackageManager.ps1
Winget version mismatch
- winget --version displays a prefix of 1.10
- winget --info shows the appx Microsoft.DesktopAppInstaller version with prefix 1.25
- Going forward we will always check version of appx instead of --verison because winget search uses the appx version
Winget Repair
- To upgrade winget it will default to using winget since it is on ALL windows installed 22H2 and above
- If winget is broken, i.e. early 24h2 version, it will use Repair-WinGetPackageManager built in function that was added in 24h2 to fix winget
> Fix Winget. Version Mismatch and Repairing.

- functions/private/Test-WinUtilPackageManager.ps1
Only a parameter in `winget search` was required.
It now works correctly everywhere:
Less buggy behavior.
- Resolves #3234
@ChrisTitusTech, **IT IS IMPORTANT THAT YOU READ THIS!!!**
This PR only focuses on fixing the version query issue. More things need to be done for the WinGet install:
- After the AppX package is installed, the script needs to be restarted
- `Repair-WinGetPackageManager` may not be present in a user's PowerShell session due to missing modules, since it doesn't come as a standard cmdlet
> [WinGet] Fix install loop

- scripts/start.ps1
- use join method to parse $argList
- use $PSCommandPath instead of $MyInvocation.MyCommand.Path
- use ScriptBlock method to create request for latest winutil.ps1 with join $argList 
- condition for $processCmd because in case when wt.exe is not available, there was double/redundant declaration of shell which lead to code mishmash (incorrect interpretation of quotes from Start-Process ArgumentList parameters 
- changes in quotes and escape characters because command where not interpreted correctly in all possible cases of $powershellCmd and $processCmd
I've encountered the same issue in multiple installation of Windows, in pwsh and powershell as described in issue #3099 when trying to run the winutil script:
```
> irm "https://christitus.com/win" | iex
Winutil needs to be run as …
```
> Fix for admin permissions elevation method

- config/themes.json
- functions/private/Initialize-InstallCategoryAppList.ps1
- functions/private/Initialize-InstallHeader.ps1
- functions/public/Invoke-WPFUIElements.ps1
- xaml/inputXML.xaml
The naming for the Header fonts size seems to have been corrupted so that the size property couldn't be referenced anymore and the Headers (for example for the app cateories) were way too small.
This PR also simplifies and unifies the creation of the "Selected Apps" button on the Apps page to use the same logic and styling as the rest of the buttons.
The Categories and Elements using the Header Font Size are now way easier to read, especially on High DPI screens
> Correct the Header Font Size

- config/tweaks.json
- Toggle that hides Windows 11 Settings Home page.
- On opening Settings, you will land on "System"
- Screenshots in attached Issue
- tested, works
- Resolves #3241, thanks @Jakob-Lindstrom
> [Toggle] Hide Settings Homepage

- scripts/main.ps1
- xaml/inputXML.xaml
This approach would guarantee that double clicking to maximize the window would only work on top row of WinUtil. It's a simple approach.. but a one that works really well (as far as I can tell).
Tested it by Double Clicking on:
- The intended areas (top row) - Works
- Other places of WinUtil, like Grids, StackPanels, Buttons of different types from toggles to normal buttons, and so on... - Did not maximize the window (as intended)
- Double Clicking on Settings/Theme popup buttons - Did not maximize the window (as intended)
Now clicking anywhere on WinUtil, other then top row, doesn't cause it to maximize the window.
This problem has been fixed by @Marterich in PR #2768, but I've faced this problem _again_ when testing out @MyDrift-user 's PR on Update Tab (PR #3230).
> Fix Double Click problem by using UIElement Names instead of Types

- config/tweaks.json
Windows Explorer automatically tries to guess the type of the folder based on its contents, slowing down the browsing experience, especially on folders with large amounts of media (photos, videos). This simple tweak sets all the folders' type to `NotSpecified`, stopping explorer from (for example) loading media thumbnails.
[Video reference (by Enderman)](https://www.youtube.com/watch?v=ctMyvJsBSzI&t=1073)
The `%USERPROFILE%\Pictures` folder (for example) no longer shows large icons with previews.
Media thumbnails are no longer loaded and displayed.
Closes #3236
None
> feat: disable explorer automatic folder discovery

- config/applications.json
In the recent past, the privacy focused Linux Distro TAILS removed the recommendation to use Balena Etcher to create there USB Keys due to privacy concerns. 
An [investigation](https://gitlab.tails.boum.org/tails/tails/-/issues/16381) on their part resulted in at least the following data being shared with the balena company
* The IP of the user
* The filename of the image, which lets Balena knows that the user is installing Tails
* The brand and model of the USB stick
https://tails.net/news/rufus/index.en.html
https://cybernews.com/privacy/tails-raises-privacy-concerns-over-balenaetcher-recommends-rufus/
- Resolves #3260
> Remove Balena Etcher due to privacy concerns

- config/tweaks.json
Get rid of the "News and Tweaks" widget in the bottom right of the taskbar more permanently and with less clicks than just hiding it.
Mentioned in #555.
With Windows 10 22H2:
- Run tweak.
- Undo tweak.
Additional tweak to "Essential Tweaks" list.
- Resolves #555
> [Tweaks] Disable "News and Interest" widget

- scripts/main.ps1
This pull request simplifies the process of obtaining window dimensions in our PowerShell scripts by eliminating the need for inline C# code. This change enhances readability and performance, making it more accessible for users who are more familiar with PowerShell than C#.
UI Loads and is responsive. 
When the initial window is bigger than the screen, it resizes as expected.
- Resolves: #3279
> Remove inline C# Type to get the window dimensions

- scripts/main.ps1
This PR refactors the Hokey handling to use switch statements instead of a long if-else structure with much repeating code and adds Comments to make the code easier to understand and to extend in the future. 
Also this PR fixes a bug regarding a Windows Warning sound being played everytime a hotkey involving "Alt" was used by explicitly telling windows if the combination was handled or not.
Also a bunch of unnecessary $_.Handled messages were removed because they were not really needed.
> Refactor Hotkey Handling

- functions/private/Find-TweaksByNameOrDescription.ps1
- functions/public/Invoke-WPFTab.ps1
- scripts/main.ps1
- Fixed an issue where the search bar did not work correctly in tabs other than "Install" (#3270)
- Added proper search functionality in the "Tweaks" tab
- Removed/Hid the search bar from other tabs where it was unnecessary
- Enhanced search bar functionality to automatically regain focus after clearing the search entry
- Modified tab behavior to reset the filtered state when switching tabs, ensuring that search filters no longer persist across tab changes
Compiled and tested. Functions as expected.
- Resolves #3270
> Fix Search bar functionality across multiple tabs

- .gitignore
- Compile.ps1
- tools/Invoke-Preprocessing.ps1
I noticed that I frequently disabled the preprocessor using the -SkipPreprocessing flag because processing all 200+ files on my VM consistently took several seconds. This effectively negated the purpose of having a preprocessor in the first place.
To address this issue, this PR removes the option to disable the preprocessor entirely. Instead, it introduces a feature that runs the preprocessor once for all files, stores their hashes in a temporary file, and only processes files that have been modified in subsequent runs. This enhancement aims to improve efficiency and streamline the preprocessing workflow.
- Removed the -SkipPreprocessing flag option.
- Removed ThrowExceptionOnEmptyFileList flag option and replaced it with a Write-Debug message
- Implemented file hashing to track …
>  Optimize Preprocessor by Implementing File Hashing for Modified Files Detection

- config/applications.json
This pull request removes OpenOffice from the application list. LibreOffice is a more modern and actively maintained alternative that is likely to meet the needs of the majority of users.
In the interest of maintaining a curated list of recommended software, I believe it is essential to streamline the application list. OpenOffice, while historically significant, has not kept pace with the advancements and features offered by LibreOffice. Therefore, it is more appropriate to recommend LibreOffice as the primary office suite for users.
Additionally, I would like to emphasize that the winutil project should focus on providing a curated selection of recommended software rather than functioning as a comprehensive graphical software installer, akin to UnigetUI. Given the nature of a PowerShell …
> Remove OpenOffice from the App list

- config/applications.json
🚨 Spotube is banned from using "Spotify™ API" 🚨
The developer of Spotube has received a cease and desist letter from Spotify USA Inc. and Spotify AB, asserting a legal threat concerning the distribution and development of any application that utilizes Spotify’s data API in conjunction with content from YouTube® to facilitate ad-free playback of music tracks. The letter contends that this specific use of the Spotify™ APIs contravenes the Spotify™ Agreements and may also infringe upon the rights of music rights holders.
Consequently, as the official maintainer of Spotube, I will immediately cease all forms of official distribution and development of Spotube that continue to employ the aforementioned 'Spotify™ APIs'
Their exact reasoning: (any) "uses of Spotify’s data API in connection with …
> remove spotube

- functions/private/Initalize-InstallAppEntry.ps1
- functions/public/Initialize-WPFUI.ps1
- xaml/inputXML.xaml
… and info options
This pull request adds a right-click context menu on the app install page, allowing users to quickly access essential actions for each app.
Right-Click Menu: Users can right-click on an app to reveal a context menu.
Action Buttons:
- Install: Initiate app installation.
- Uninstall: Remove the app directly.
- Info: Open the app's web page for more details.
The context menu, which includes Install, Uninstall, and Info buttons, is created once and dynamically updated with the relevant app information and button positioning. This approach reduces the number of WPF elements from over 1000 to just 5, significantly improving loading times compared to the initial redesign
> Add Right-Click Action on App Install Page

- config/tweaks.json
Added a small note to make it clear that enabling this will disable Windows Spotlight on Lock Screen.
Relates to issue #3203 - does not resolve it outright but gives fair warning of a hidden and unexpected side effect.
> Windows Spotlight warning

- functions/private/Find-AppsByNameOrDescription.ps1
- scripts/main.ps1
This PR introduces a delay for the search field functionality, implementing a 300ms debounce effect. With this change, the UI will only initiate a search for matching entries after the user has stopped typing for 300 milliseconds.
This enhancement improves the responsiveness of the user interface by preventing the script from filtering the applications on every keystroke. As a result, users will experience a smoother and more fluid interaction when searching for entries.
Also this changes allows us to include the app description in the fields being searched. 
Resolves: #3065
> Implement search bar debounce functionality to improve UI responsiveness

- xaml/inputXML.xaml
When maximized, the GUI currently occupies the entire screen, including the taskbar. This PR changes that ensuring the window behaves like a standard maximized application, respecting the taskbar area
Compiled and tested. Functions as expected
> Fix: Window maximization behavior overlapping taskbar

- config/applications.json
- functions/public/Initialize-WPFUI.ps1
- Update DDU Winget Reference
- Remove Samsung Magician as it has been removed from the winget repos. (also remove the Chocolatey install target, as the install logic dosnt handle it very well when the winget target does not exist. (requires a check that the action is not null) and also because samsung magician does not support a silent installation which means that chocolatey has to fallback to a autohotkey script which is error prone and breaks the "silent" install flow of winutil. Also the version provided by chocolatey is not up to date anymore.)
- Resolves #3300
- Closes #3353
> Fix App references

- config/tweaks.json
Fixes a problem where the explorer sometimes would not restart automatically but instead showed a interactive prompt to the user to confirm the restart.
- Resolves #3295
> Refactor process termination for explorer.exe in tweaks.json

- config/tweaks.json
`G:\projects\winutil\docs\dev\tweaks\Essential-Tweaks\Tele.md` is this file can be auto-updated ?
`.\Compile.ps1` do not update it.
> The MouseHoverTime setting does not appear to have any relevance to Telemetry

- config/tweaks.json
This PR separates the removal of `Home` and `Gallery` in the Explorer sidebar into two different options. For people like me who prefer to keep the Gallery but not Home, or the other way around.
Compiled and tested. Functions as expected
> refactor[Tweak] Separate removal of Home and Gallery from explorer

- config/tweaks.json
This PR resolves the issue where Copilot cannot be fully removed on 24H2. It introduces additional registry tweaks that block Copilot's runtime execution, prevent system availability, and remove shell integration
Compiled and tested. Functions as expected
- Resolves #3404
- Resolves #3393
> [Tweaks] Updated Copilot Removal 

- config/tweaks.json
- Minor formatting change for `AllowTelemetry` tweak.
- Added `PeriodInNanoSeconds`, which is related to "Feedback Frequency". When setting it to "Never", this should also be deleted (if present).
- Added new policy entry for `DODownloadMode`, in addition to the normal `Config` registry path one, and set the value to `0` instead of `1`. `0` completely disables "Delivery Optimization" and ensures updates are only download from official Microsoft servers. `1` allows for local network downloads, which can result in upload activity randomly on Windows.
No extensive testing needed.
No major impacts.
N/A
N/A
> Updates to the "Disable Telemetry" tweak

- config/tweaks.json
This PR adds an option to control the Resume feature introduced in Windows 11 24H2:
It works successfully on Windows 11 24H2.
A new feature
No issues resolved
Since this is my first tweak, feel free to provide feedback in case I screwed up with the properties.
> [Tweaks] Cross Device Resume

- config/tweaks.json
This adds a comment to the Razer tweak clarifying that it will also block other third-party drivers installation, since it modifies REG keys used by other drivers too (from Windows Update).
Additionally, I've removed `SearchOrderConfig` from the Disable Telemetry tweak, because it can undo the Razer tweak and the default is already `1`, so no need to re-set it.
I've also changed instances of "explorer" to "Explorer" (uppercase) and some other misc. comment/visual changes.
No extensive testing needed.
No major impact.
N/A
N/A
> Update to Razer tweak + comments updates

- config/tweaks.json
Removed Brave Sync from the options that were being disabled by the Brave debloat tweak, because it isn't really an annoyance like the others, where you need to sign up to a service (e.g. VPN) but rather a fairly solid option to sync browser data across multiple devices. 
Also it was not mentioned in the description that the setting would be affected in the first place.
https://support.brave.app/hc/en-us/articles/360059793111-Understanding-Brave-Sync
- Resolves #3527
For anyone who wants to reenable the sync feature, manually, please run the following command in an administrative Powershell/Terminal window. 
`Remove-ItemProperty -Path "HKLM:\SOFTWARE\Policies\BraveSoftware\Brave" -Name "SyncDisabled"`
> Omit Brave sync on Brave debloat

- config/themes.json
- functions/private/Invoke-WinUtilFontScaling.ps1
This improves the Font scaling function from the PR I created couple of weeks ago. #3505
This now scales the UI elements with the font such as buttons and search bar.
Tested on 24H2
- Resolves #3501 
There are some things that still don't work as expected such as the sidebar and topbar doesn't scale and causes text overflow on large scaling options and the search icon in search bar doesn't align after applying scaling because it has a fixed margin. I couldn't fix them without breaking stuff or overcomplicating things.
I think 150% scaling is the sweet spot but I still haven't tested it on a high-res monitor so I'm not sure.
> Fix scaling of UI Elements when applying Font Scaling

- config/applications.json
The current winget package name for Session is way out of date, the new package name is Session.Session.
Ensured that the previous package name was out of date before attempting a winget search session, which brought up the correct page. Installed manually and obtained the correct piece of software.
Ensures that individuals that are seeking to install Session from this tool, that they are not met with the package not found error during the install process.
- N/A
N/A
> [Applications] Fixed invalid winget install name for the Session application.

- functions/public/Invoke-WPFInstall.ps1
- functions/public/Invoke-WPFUpdatesdefault.ps1
- functions/public/Invoke-WPFUpdatesdisable.ps1
This PR enhances the password prompt logic during application installs (e.g., Spotify) triggered by the script. Previously, entering incorrect credentials caused the prompt to close and halted the install script, forcing users to restart the process.
Key improvements:
Users are now re-prompted for credentials if authentication fails, instead of the script halting.
The process continues until the correct password is entered or the user cancels.
Prevents unnecessary script exits and improves overall user experience when installing password-protected applications.
Tested:
Tested with both valid and invalid credentials in a CLI (text prompt) environment to confirm retry logic works as intended.
> Fix: retry password prompt on failure to prevent script halting

- functions/microwin/Invoke-MicrowinGetIso.ps1
- scripts/main.ps1
- xaml/inputXML.xaml
Remove mentions of Windows 11 Edition and pull latest edition and pull all editions without the extra variables in the command.
Tested locally and fully works
People now won't only see 1 option on the Windows 11 Version.
- Resolves #
> Remove mentions of Windows 11 Edition and pull latest

- functions/private/Test-WinUtilInternetConnection.ps1
`-TimeoutSeconds` is not a parameter in Test-Connection for PWSH 5.
It works.
@ChrisTitusTech, at least test whatever BS AI spits at you...
> [Offline] Fixed invalid command in PWSH 5
