ChrisTitusTech/winutil

winutil.ps1
Code format using VS Code PowerShell Extension [(link)](https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell)
open `command palette (ctrl + shift +P)` in VS Code and use Format Document
=> Code format using powershell VS code extension

MainWindow.xaml, winutil.ps1
Added Uncheck All option
optimised uncheck during install click
=> Added Uncheck all button in the Install tab

winutil.ps1
=> Throw warning if no programs are selected for installation

MainWindow.xaml
fix simple typo:
from `buisness` to `business`
=> fix typo buisness to business

winutil.ps1
If you dont add -NoRestart to Enable-WindowsOptionalFeature it prompts you every time it tries to install something.
=> Added  -NoRestart to WindowsOptionalFeature

winutil.ps1
This PR optimizes the exception handled of the User System where UAC is enabled.
During install / upgrade click on install tab, The UAC pops up. If the User denies it. proper message is not shown, sometimes empty message box appears, and even the info is misreported. Handled those cases.
Steps to simulate.
1. select any 1 program and click on `Start Install`
2. click `no` on UAC prompt,
3. The message box will display messages with the program installed.
1. click on `Upgrade Installs`
2. click `no` on UAC prompt,
3. The message box will display message as Done
=> Handled UAC exit on install and upgrade

MainWindow.xaml, README.md, applications.json, winutil.ps1
coming from linux, this project is kind of confusing for me, I hope I haven't missed anything. this should install rust and alacritty from winget.
the packages on there are quite outdated when I browsed it, some are even behind apt while some others straight up don't show up in PATH. perhaps something has to be done... at least it's working so far, I managed to install the two packages on my windows laptop.
=> added software development related packages

MainWindow.xaml, README.md, winutil.ps1
Corrected spelling mistake of registry key.
=> Fixed some errors

.gitignore, MainWindow.xaml, applications.json, winutil.ps1
This changes were made to this files: **application.json** for winget, **MainWindow.xaml** for the checkbox and **winutil.ps1** to check if the checkbox is selected or not. I aslo added .idea to the **.ignore** file because I'm using Intellij Idea and I didn;t want the .idea folder to be in the remote repo.
=> Added Twinkle Tray.

MainWindow.xaml, winutil.ps1
wasnt on my branch but i just saw it.
otherwise it works 👍🏻
=> Someone duplicated DisableUAC on your branch

MainWindow.xaml, winutil.ps1
- Added Undo for TPM and UAC
- Added TPM Check Skip
- Used the actual right values for GameDVR and FSO
- Added Long Paths
Re of https://github.com/ChrisTitusTech/winutil/pull/177 bc Github closed it after i needed to Rebase it.
=> Longer Thing

winutil.ps1
This fixed the issue I was having in https://github.com/ChrisTitusTech/winutil/issues/189#issue-1384663355
=> Move winget install to user temp folder

winutil.ps1
As Above
EDIT:
Verified its working 100%.
=> Implement Check if Path for TPM Exists

MainWindow.xaml, winutil.ps1
Added option to Disable Notifications and Action Center under Misc Tweaks section
also added Enable Notifications and Action Center in undo tweaks
I tested this features multiple times on different vms it works fine for me
=> Added option to Disable Notifications and Action Center : Done FR#23

MainWindow.xaml, winutil.ps1
Added option for remove microsoft edge
i put script that remove microsoft edge in my github repo and in this script i added option for remove microsoft edge that run that bat file through 
iwr -useb https://raw.githubusercontent.com/padsalatushal/Edge-Removal/main/Edge_Removal.bat | iex
i tested this it work fine but for some reason it work slow in vm but it work fast in bare matal windows
also fix minor issue in line 1078
=> Added option for remove microsoft edge

MainWindow.xaml, winutil.ps1
Added Dark mode 
Enable and Disable for Dark mode
i think the gui button for enable & disable is not that good but it can be improve
=> Added Dark Mode

MainWindow.xaml
* Test 2022 (#240)
* Merge Gaming Tweaks and Temp Files Addition (#193)
* Update README.md
* QOL Terminal - Win Update Revamp
* Fix Flickering
* Quick Fix - UAC Property error
* Network Performance Tweak
* Gaming Tweaks
* Delete Temp Files Addition
* Delete Temp Files GUI
* Added LibreOffice to applications.json and winutil.ps1 to fix #171 (#178)
* Fixes missing LibreOffice (#171)
Added missing LibreOffice to fix issue #171.
* Fixes missing LibreOffice (#171)
Added LibreOffice to winutil.ps1 to fix issue #171.
* Create `FUNDING.yml` (#182)
* Longer Thing (#186)
* redid the whole thing
* man
* Tweaks to change
I like most of these but adding the UAC back in, Disabling Long Paths, and removing TPM properties aren't approved in the default essential tweaks. This should have been put into the …
=> cleanup and rebase test (#244)

KnownIssues.md
- The issues listed in KnownIssues.md were broken due to the issues tab in the previous repo being removed.
- Replaced with issues in this repo that apply to the issues, if there were any
- I think this issue could be applied to the main branch without worry, but I'll leave that up to you.
=> Replace Broken Issue Links in KnownIssues.md

winutil.ps1
- Checks for an ooshutup10.cfg file in the current directory and uses it if found
- This allows users to use custom config files if they wish
=> Implement check for local ooshutup10.cfg file

MainWindow.xaml, runspace.ps1, winutil.ps1
Added a dropdown menu box for choosing DNS like google, cloud flare, level3, and OpenDNS. After selecting when the run tweak button press changes DNS for all connations. The default value is a default that does not change anything.
=> added option to change dns

config/applications.json, runspace.ps1
Reverts ChrisTitusTech/winutil#310
=> Revert "Add missing program in applications.json file"

MainWindow-runspace.xaml, MainWindow.xaml, config/tweaks.json, winutil.ps1
Adds tweaks to toggle mouse acceleration.
=> Add Disable and Enable Mouse Acceleration Tweaks

MainWindow.xaml, config/tweaks.json, winutil.ps1
in response to issue #366 , added buttons for adding and removing the Ultimate Performance Power Plan.
needs testing on more than just windows 10 22h2.
=> Add Ultimate Performance add/remove buttons

config/helperscript.ps1, pester/winutil.Tests.ps1, winutil.ps1
Somehow a bracket got axed in the merge. Updated it for the latest config file and is working again. 
Though I noticed the pipeline has fewer tests than when ran manually. I will have to play around with this some more since the nunit xml was too large to upload through the job.
=> Fix of the unit tests

winutil.ps1
- Done by enabling "Trim Trailing Whitespace" setting in VSCode, then saving the file
=> Trim Trailing Whitespace

.gitignore
- Organized into categories
- Added some files and folders that often cause issues
=> Add to and organize .gitignore

winutil.ps1
Added a progress bar for the winget install. I also added the wait switch to start-process to make things a little smoother
Windows Powershell
Powershell Core
=> add progress and add wait to start-process

winutil.ps1
[Let user decide if he wants to install Chocolatey.
=> Update check for Chocolatey 

winutil.ps1
Migrated the switch tabs function from runspaces to main script
=> Switch-Tab function

winutil.ps1
Merry Christmas @ChrisTitusTech and @Carterpersall I found a way to have the GUI remain responsive and install winget in a separate process. Let me know what you think, only downside is you loose the popup at the end but gain the ability to close the GUI if you desire.
=> add responsive winget installs

MainWindow-runspace.xaml, MainWindow.xaml, config/applications.json
- Add golang, an installation option in development list
=> Add Application in Development

winutil.ps1
Figured out a way to make the process check more reliable and structured the process checker to have greater compatibility for future processes that use this method. Then moved the process check to the beginning of the button script.
Also fixed some formatting
=> Updated winget functions

config/tweaks.json, pester/winutil.Tests.ps1, winutil.ps1
Working on moving some functions of the script into functions for easier pester testing and adding error handling
=> Functions and error handling

MainWindow-runspace.xaml, MainWindow.xaml
So many capitalisation and grammar issues. I fixed most of 'em :) (I might have missed some but I am also a human).
=> Fix grammar

functions/public/Invoke-WPFtweaksbutton.ps1, functions/public/Invoke-WPFundoall.ps1
Added check for no checked tweaks plus formatting
=> Tweaks Check

config/feature.json, functions/private/Get-WinUtilCheckBoxes.ps1, functions/private/Invoke-WinUtilFeatureInstall.ps1, functions/public/Invoke-WPFFeatureInstall.ps1
Moved features to the config files and updated to use runspaces. GUI should no longer lock up 😎
=> Features Migrated to config and runspaces

config/applications.json, winutil.ps1, xaml/inputXML.xaml
This is a fairly simple commit, added the option to install WinRAR and Ubisoft Connect.
In applications.json
-  Added Package Names for the winget & choco
In inputXaml
- Added the Install option
And finally in the main script itself, added the options within the xml and json.
=> Add Ubisoft Connect & WinRAR as install options.

config/applications.json, xaml/inputXML.xaml
The developers of atom decided to sunset it a while ago so I thought it should probably be removed from this tool
https://github.blog/2022-06-08-sunsetting-atom/
=> Removed Atom due to it having been sunsetted

config/applications.json, winutil.ps1
=> Fix #649 : revo uninstaller package name 

functions/public/Invoke-WPFPresets.ps1, winutil.ps1
there is a typo on "functions/public/Invoke-WPFPresets.ps1" that's why  import export feature on tweak section is not working. but now it's working fine :).
=> Fix import export feature on tweak section

config/tweaks.json
=> fix wlansvc service

config/tweaks.json
fix #735 , #737 , #756 , #721 , #755
=> set Winmgmt service to automatic

functions/public/Invoke-WPFUltimatePerformance.ps1, winutil.ps1
* Fix power profile query
* fix syntax
* fix
* Update Invoke-WPFUltimatePerformance.ps1
* Update winutil.ps1
* power profile fix
=> Fix power profile (#766)

functions/public/Invoke-WPFButton.ps1, functions/public/Invoke-WPFFixesNetwork.ps1, winutil.ps1, xaml/inputXML.xaml
=> add reset network with netsh

config/applications.json, winutil.ps1, xaml/inputXML.xaml
* Prism Launcher - Custom FOSS minecraft launcher
* Gsudo - Command line program that allows you to elevate a program as admin.
* WingetUI - Graphical front end for winget, chochlatey and scoop
=> Adding 3 programs to the install tab

config/tweaks.json, functions/private/Invoke-WinUtilTweaks.ps1, winutil.ps1
=> add undoscript feature + implement it on every tweaks

config/applications.json
=> Fix packages name

scripts/start.ps1, winutil.ps1
#816 : check if the script is running as admin or not and if not then it attempts to relaunch with admin privilege.
=> check for Admin and attempt relaunch

config/applications.json, winutil.ps1, xaml/inputXML.xaml
=> add-docker-desktop

functions/private/Invoke-WinUtilCurrentSystem.ps1, winutil.ps1
=> Fix 'Get Installed' for multiple-dependency apps

config/applications.json, winutil.ps1, xaml/inputXML.xaml
=> Program Update: Replace Origin with EA App

edgeremoval.bat
In the last pull request i wrote "$start_menu_progams" instead of "$start_menu_programs" so I am sorry for the unneeded spam.
=> Fixed consistency in variable names and values inside edgeremoval.bat

config/tweaks.json, edgeremoval.bat, winutil.ps1
Github user "padsalatushal" forked the script from the original owner "AveYo" and "padsalatushal" did not update it for almost two months. You can see that its the same script because "padsalatushal" referenced the original owner in the README.md in the repo [here](https://github.com/padsalatushal/Edge-Removal#resources). Here is a more recent script with my modifications to the "extra cleanup" part.
padsalatushal's repo: https://github.com/padsalatushal/Edge-Removal
AveYo's repo: https://github.com/AveYo/fox
=> Updated Edge Removal Script to the more up-to-date one.

config/tweaks.json
=> fix when User name have space

config/applications.json, winutil.ps1, xaml/inputXML.xaml
This fixes #940 by removing OperaGX, fixing alphabetization, and removing my instance of Neovim which I didn't notice was added recently.
=> Add Applications (Fixed)

config/applications.json, winutil.ps1, xaml/inputXML.xaml
Add Bulk Crap Uninstaller to Utilities
=> Add application

config/tweaks.json
Disables the icons on the taskbar for:
- Chat/Teams
- Search Bar
- Task View
- Widgets
=> Disables some icons on the taskbar 

config/applications.json, winutil.ps1
=> Update autohotkey id

config/applications.json, winutil.ps1
=> fix package name

README.md, config/applications.json, config/tweaks.json, functions/private/Set-WinUtilRestorePoint.ps1, functions/public/Invoke-WPFUpdatesdefault.ps1, functions/public/Invoke-WPFUpdatessecurity.ps1, winget.ps1, winutil.ps1, xaml/inputXML.xaml
=> Test 2023 08 09

config/applications.json, functions/private/Invoke-WinUtilCurrentSystem.ps1, winutil.ps1, xaml/inputXML.xaml
1. Added DDU
2. Sorted the application list alphabetically for easier navigation
3. Fixed some typos, indentation and format issues for more readability
=> Application Sort - DDU - Change in Runspace

config/tweaks.json, xaml/inputXML.xaml
Added tweaks to disable and enable IPv6.
=> Added tweaks for IPv6

config/applications.json, xaml/inputXML.xaml
https://github.com/M2Team/NanaZip
=> Add NanaZip

config/applications.json, xaml/inputXML.xaml
Added Jellyfin Media Player and Jellyfin Server under Multimedia Tools
=> Added Jellyfin Media Player and Server

config/applications.json, xaml/inputXML.xaml
Added the Okular document viewer, made by the KDE team.
=> Added Okular document viewer

config/applications.json, xaml/inputXML.xaml
Same one as #1057 But remove chocolatey package due to there is no package in  chocolatey repo right now
=> Add Guilded into Communication Tab

xaml/inputXML.xaml
Updated inputXML.xaml to account for the addition of the SuperF4 software into applications.json.
=> Update inputXML.xaml to add SuperF4

config/applications.json, xaml/inputXML.xaml
Add Ventoy USB software. This software afaik is only packaged using Chocolatey.
=> Add Ventoy (Chocolatey Only Package) & .NET Core Runtime (Winget & Chocolatey) 

config/applications.json, xaml/inputXML.xaml
Based on the discussion in #1074, I have raised a new PR  to add only MSI Afterburner to the list
=> add MSI Afterburner

config/applications.json, winutil.ps1, xaml/inputXML.xaml
Hey gang!
I love using this script, and having found need to use it frequently, I thought I would throw in my hat into the ring and add some of my own! I have added Duplicati (a backup program), OpenVPN Connect (a client to connect to a VPN), KDE Connect (A program made by KDE to sync up your phone and computer), Paint.net (a image editor that I quite like!), and Oracle VirtualBox.
I have also tested the script to make sure all the packages are correct.
This is the first time I've contributed to a public repository, so I hope I have followed all the rules for contributing! If I need to change anything, feel free to let me know :) !
=> Added Programs to the Install List

config/applications.json, xaml/inputXML.xaml
This adds KDE Dolphin File Manager and Sublime Merge.
=> Add 2 Applications

config/applications.json, xaml/inputXML.xaml
Hi Chris! First of all, thanks for the awesome tool you created.
Adding [Mercury Browser](https://github.com/Alex313031/Mercury) to the browser section. 
I hope I did everything right.
Peace ✌️
=> Add Mercury Browser from Alex313031

config/applications.json, xaml/inputXML.xaml
This application can be used to split, combine PDF files. The application is [open source](https://github.com/torakiki/pdfsam) and I am personally using it on Windows and Linux. Thing you may not like: there exists a paid version (not included here) with more features. I am not affiliated with this application and would be interested in something else if it's better.
=> Add PDFsam Basic

config/applications.json, xaml/inputXML.xaml
Adds new applications:
[Angry IP Scanner](https://angryip.org/) - Network scanner
[Calibre](https://calibre-ebook.com/) - E-book manager
[HeidiSQL](https://www.heidisql.com/) - Database management tool
[Linphone](https://www.linphone.org/) - VoIP software and SIP client
[Nextcloud Desktop](https://github.com/nextcloud/desktop) - Official Nextcloud client application
[OpenRGB](https://openrgb.org/) - RGB lighting control, independent from manufacturer software
[ownCloud Desktop](https://github.com/owncloud/client) - Official ownCloud client application
=> Add new applications

README.md
* #useage->issues: nested in a spoiler
* #useage->issues: 
* #useage->issues: added https:// in front of the christitus.com/win link so people can easily click it to see if it loads
* #tutorial: updated the tutorial video with your new one, I also used a different ytimg link so it does not have black bars at the top and bottom, it that's too high res (thus too big) I can make it smaller if you ask 👍
* #contributing: clarified the branches with codeblocks and make them the same capitalization, added a link to the infamous [firstcontributions](https://github.com/firstcontributions/first-contributions#readme) guide
=> readme refactor: offline execution tutorial, wording, small fixes

config/applications.json, winutil.ps1, xaml/inputXML.xaml
Carnac = https://github.com/Code52/carnac
ImgBurn = https://www.imgburn.com/
Nmap = https://github.com/nmap/nmap
PrucaSlicer = https://github.com/prusa3d/PrusaSlicer
Tailscale = https://github.com/tailscale/tailscale
Zotero = https://github.com/zotero/zotero
=> Add 6 Programs

config/applications.json, config/themes.json, functions/private/ConvertTo-Icon.ps1, functions/private/Get-LocalizedYesNo.ps1, functions/private/Get-Oscdimg.ps1, functions/private/MicroWin-Helper.ps1, functions/public/Invoke-WPFButton.ps1, functions/public/Invoke-WPFCloseButton.ps1, functions/public/Invoke-WPFGetIso.ps1, functions/public/Invoke-WPFMicrowin.ps1, functions/public/Invoke-WPFShortcut.ps1, scripts/main.ps1, winutil.ps1, xaml/inputXML.xaml
Lots of Microwin fixes and Program Additions
=> Test 2023 12 19

functions/public/Invoke-WPFGetIso.ps1, winutil.ps1
=> [Fix]: MicroWin finds but fails to use system oscdimg

README.md
In reference to:
https://github.com/ChrisTitusTech/winutil/issues/1327
=> Update README for India blocking

Compile.ps1, functions/private/MicroWin-Helper.ps1, functions/public/Invoke-WPFMicrowin.ps1, winutil.ps1, xaml/inputXML.xaml
- Added Version to App so you know if you are up to date
- Microwin Default modifications Keep Security and Defender @CodingWonders 
- Scrollbar Tweaks @munkk01
=> Test 2024 01 02 Main Merge

config/applications.json
Added the following software:
- Development
- HxD Hex Editor
- Games
- PS Remote Play
- Virtual Desktop Streamer
- Multimedia Tools
- Plex Media Server
- Utilities
- Total Commander
- 1Password
- Raspberry Pi Imager
- BitComet
- Samsung Magician
- Windows PC Health Check
=> feat: Add more software choices

config/applications.json, winutil.ps1
Modify logseq release url to logseq.com
Add .net runtime 8.0
=> change logseq url and add .net 8

config/applications.json, winutil.ps1
=> fixed description for golang

config/applications.json
Identifiers:
- Winget: Parsec.parsec
- Chocolatey: parsec
Closes #1157
=> add Parsec to installable applications (#1157)

config/applications.json, winutil.ps1
Removed the Files application. The original is no longer available via Winget.
Two open issues discuss this.
=> remove files application

config/applications.json, winutil.ps1
- [Authy](https://authy.com/) : Simple and cross-platform 2FA app
- [SyncTrayzor](https://github.com/canton7/SyncTrayzor) : Windows tray utility / filesystem watcher / launcher for Syncthing
- [BleachBit](https://www.bleachbit.org)
- [Espanso](https://espanso.org) : Cross-platform and open-source Text Expander
- [PDF24Creator](https://tools.pdf24.org/en/) : Free online/desktop PDF tools
- [lazygit](https://github.com/jesseduffield/lazygit/) : Simple terminal UI for git commands
- [wezterm](https://wezfurlong.org/wezterm/index.html) : Powerful cross-platform terminal emulator and multiplexer
- [ripgrep](https://github.com/BurntSushi/ripgrep) : Fast and powerful commandline search tool
- [fzf](https://github.com/junegunn/fzf) : A command-line fuzzy finder
- [Google …
=> Add some useful programs and fix an app's url

config/applications.json
Add Power BI program to Microsoft Tools category
=> Feat: Add Microsoft Power BI program

config/applications.json, winutil.ps1
https://www.ferdiapp.com/ is not working, correct the same to https://ferdium.org/
=> Fix Fredium App Link

functions/public/Invoke-WPFFeatureInstall.ps1, functions/public/Invoke-WPFGetInstalled.ps1, functions/public/Invoke-WPFInstall.ps1, functions/public/Invoke-WPFUnInstall.ps1, functions/public/Invoke-WPFundoall.ps1
$DebugPreference is not sent as different argument
=> Calling Invoke-WPFRunspace with argument fix

xaml/inputXML.xaml
Saw this in your latest video on winutil and it bugged me. So here I am. There's a chance you may reject this but at least I tried.
=> Fixed typo: latancy to latency

config/applications.json
https://github.com/Vencord/Vesktop
=> Add Vesktop to applications.json

config/applications.json
Add [Mumble](https://www.mumble.info/) to Communications category.
=> Add Mumble

config/applications.json
WinMerge is an Open Source differencing and merging tool for Windows.
=> Added WinMerge Application in Development category.

config/applications.json
* Fix Nanazip link
* Add syncthingtray app
=> Fix Broken Link and add syncthingtray

config/feature.json, config/tweaks.json, scripts/main.ps1, winutil.ps1, xaml/inputXML.xaml
- remove tweaks and feature items from inputXML.xaml file
- add context and descriptions to tweaks.json and feature.json files
- add type to items like button, toggle, combobox to automate add to inputXML.xaml file
- change the main.ps1 file to add not just application items but also tweaks and features to inputXML.xaml file
- in application.json WPFInstallOPAutoClicker has a panel as 5, that is why the original version does not show it
my version will create 6th column just for that if you change it to 4 application tab will be reduced to 5 column
=> tweaks and fetures tabs clean up automation from inputXML.xaml

functions/public/Invoke-ScratchDialog.ps1, functions/public/Invoke-WPFButton.ps1, functions/public/Invoke-WPFGetIso.ps1, xaml/inputXML.xaml
I think i finally got it. 🥇 
If its still making problem feel free to implement this idea yourself :)
=> Choosing Alternate Scartch Path and Busy Messages

config/feature.json, functions/public/Invoke-WPFButton.ps1, functions/public/Invoke-WPFRemoveAdobeCC.ps1, xaml/inputXML.xaml
I have pulled in all the latest changes and added the new button at the file `features.json`, as requested from the livestream.
=> RE: Add Adobe Creative Cloud Cleaner tool

config/applications.json, scripts/main.ps1, winutil.ps1
As KonTy suggested, I modified the application tab so that applications are evenly distributed to 5 columns. That way we don't need panel property in the application.json file.
=> application are evenly distributed to 5 columns

config/feature.json, winutil.ps1
The JSON is poorly formatted. In my machine this resolved the issue. Really weird, the changes I made were not necessary for it to function
=> Fix config tab

config/tweaks.json, functions/private/Get-WinUtilToggleStatus.ps1, functions/private/Invoke-WinUtilStickyKeys, functions/public/Invoke-WPFToggle.ps1, winutil.ps1
Adds a toggle to enable/disable sticky keys
=> Add toggle "sticky keys"

config/applications.json, config/feature.json, config/tweaks.json, functions/private/Get-WinUtilToggleStatus.ps1, functions/private/Invoke-WinUtilStickyKeys, functions/public/Invoke-WPFToggle.ps1, winutil.ps1
Fixing Config JSON error Thanks @Yuuh15 
Adding Toggle for Sticky Keys
Also adding some Dev Tools
=> Test 2023 02 02

config/applications.json, functions/public/Invoke-WPFRunAdobeCCCleanerTool.ps1, winutil.ps1, xaml/inputApp.xaml
`DevToys` doesn't have a proper `winget` Id unlike other programs. I had modified to the correct one as mentioned in #1685
=> fix DevToys winget id (#1685)

config/applications.json, xaml/inputApp.xaml
4 broken URLs fixed
8 URLs updated for better information
22 names updated to match creator formatting
=> Fixed/improved URLs and updated software naming based on creator formatting

config/applications.json, config/themes.json, config/tweaks.json, functions/private/Install-WinUtilProgramWinget.ps1, functions/private/Invoke-MicroWin-Helper.ps1, functions/private/Invoke-WinUtilGPU.ps1, functions/private/Test-WinUtilPackageManager.ps1, functions/public/Invoke-WPFGetIso.ps1, functions/public/Invoke-WPFInstall.ps1, functions/public/Invoke-WPFMicrowin.ps1, scripts/main.ps1, winutil.ps1, xaml/inputApp.xaml, xaml/inputXML.xaml
- New github action - Closing old issues
- Fix for file creation in microwin and automation fixes @CodingWonders 
- Fix theme for no GPU low spec PCs @blusewill 
- Misc Fixes from @og-mrk 
- Fix typos and Grammer
- Large refactor and removal of dynamic GUI elements (Moved to Compile.ps1 script) for more performance
=> Test 2024 02 07 refactor noapps

config/applications.json, xaml/inputApp.xaml
Added [TightVNC](https://www.tightvnc.com/) Witch was requested in issue https://github.com/ChrisTitusTech/winutil/issues/1718
This was done in applactions.json and was tested to ensure it ran on my local sytems with no issues
Also installed it via the util to ensure that the package names are correct and it installed fine
Resolves: https://github.com/ChrisTitusTech/winutil/issues/1718
=> Add tightvnc to address issue #1718

functions/private/Get-Oscdimg.ps1
Read the commit patches for exact details on the changes...
=> Fix typo in 'Get-Oscdimg.ps1' Private Function

functions/private/Update-WinUtilProgramWinget.ps1
This fixes the Update issues in #1181 
Which is some function needs to be changed in the `Update-WinUtilProgramWinget.ps1`
=> Fixes Update.

config/preset.json
=> Remove the Non-existing 'WPFMiscTweaksPower' found in the 'preset.json' File

functions/private/Invoke-MicroWin-Helper.ps1, functions/public/Invoke-WPFMicrowin.ps1, winutil.ps1
This PR continues the conversion journey of DISM commands into PowerShell cmdlets from the DISM module. All commands have been converted successfully, except for the cleanup command, which is unavailable in PowerShell.
I've also renamed the variables in some functions so that everyone can distinguish them more easily. Not all refer to AppX packages.
Please feel free to report any issues here or to bring any improvements.
=> Finished conversion of DISM commands into DISM cmdlets

config/applications.json
Added 2 apps:
- Microsoft Power Automate Desktop (https://www.microsoft.com/en-us/power-platform/products/power-automate): Microsoft Power Automate Desktop is a powerful process automation platform that allows you to create, manage, and optimize automated workflows.
- Swift toolchain (https://www.swift.org/): Swift is a FOSS, general-purpose programming language that’s approachable for newcomers and powerful for experts.
=> Add Microsoft Power Automate and Swift toolchain

edgeremoval.ps1, winutil.ps1
-Adds additional functionality, such as removing AppX packages and redirecting Edge shortcuts, to provide a more thorough removal of Microsoft Edge and related components
-comments to explain each section of the script
-error handling (-ErrorAction SilentlyContinue) to handle potential errors
=> editing edgeremoval.ps1

config/tweaks.json
This was pointed out in GitHub issue https://github.com/ChrisTitusTech/winutil/issues/1838
=> Fix 'Disable Storage Sense' Tweak in 'tweaks.json' File

config/tweaks.json
Simple Addition to https://github.com/ChrisTitusTech/winutil/pull/1837 PR
=> Add 'UndoScript' to 'Enable End Task With Right Click' Tweak in 'tweaks.json' File

functions/private/Test-WinUtilPackageManager.ps1
- Changed version check for Winget to keep Winget updated to latest version and a couple formatting fixes.
- Should mitigate issues, such as, #1824
=> Winget Version Check Fix

config/tweaks.json
This was pointed out in Issue #1798
Resolves https://github.com/ChrisTitusTech/winutil/issues/1798
=> Add 'UndoScript' to 'Disable Hibernation' Tweak in 'tweaks.json' File

config/applications.json
List of added apps:
- Microsoft Azure Data Studio
- Java 11, 17, 18, 19 runtimes
- Microsoft SQL Management Studio
=> Add apps from #250

config/tweaks.json
This was pointed out in https://github.com/ChrisTitusTech/winutil/issues/1848 issue
Resolves https://github.com/ChrisTitusTech/winutil/issues/1848
=> Fix Robocopy Not Copying for Users who have a Space in their name

config/applications.json
Satisfies a request made in [this comment](https://github.com/ChrisTitusTech/winutil/issues/1782) on Programs Tracking List ([a link to it](https://github.com/ChrisTitusTech/winutil/issues/1782)).
=> Add 'betterbird' App to 'applications.json' File

config/applications.json
Windhawk
The customization marketplace for Windows programs
https://www.youtube.com/watch?v=ijG0nXnO2gQ
=> Update applications.json (Windhawk)

config/applications.json
perhaps a good "tweak" that could be added to Tweaks section down the road.  project is foss... could be   a good resource for someone with enough skills.
in the meantime, does what it says it will, and does it well.
=> add MSEdgeRedirect to applications.json

functions/private/Test-WinUtilPackageManager.ps1
Should fix issue https://github.com/ChrisTitusTech/winutil/issues/1881
Thanks to @Marterich for suggesting a fix by using Proper Error-Handling 👍
=> Fix Winget Detection by doing Proper Error Handling using a Try-Catch

functions/public/Invoke-WPFMicrowin.ps1, xaml/inputXML.xaml
This PR adds the ability to import drivers from the active installation to the MicroWin image:
<p align="center">
</p>
This is the introductory bit, focusing on the core technology of this feature. More additions will come in the future.
=> Added ability to import drivers

config/applications.json
Adds:
[NetLimiter](https://www.netlimiter.com) 
[OneCommander](https://www.onecommander.com)
[Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming)
[Equalizer APO](https://sourceforge.net/projects/equalizerapo)
[FreeFileSync](https://freefilesync.org)
[Elgato Stream Deck](https://www.elgato.com/uk/en/s/downloads)
[Stardock Curtains](https://www.stardock.com/products/curtains)
I couldn't test it myself because I'm new and not entirely sure what to do, but I am willing to learn and apologies if I made a mistake. Keep up the astounding work.
=> Test 2024 04 20 2 | 7 additions to applications.json

config/applications.json
First contribution so please tell me if I did something wrong
As the commit message I added [GlazeWM](https://github.com/glzr-io/glazewm) to the applications.json
=> add GlazeWM to applications.json

config/applications.json
- Fixed the name and description for Element to reflect the name of the client, rather than the underlying technology-Matrix. (Partial solution to #1897)
=> Update name and description for Element

config/applications.json
=> Added ForceAutoHDR application to applications.json

config/applications.json
Added Godot Engine (https://godotengine.org/).
Godot Engine is a free, open-source 2D and 3D game engine with a focus on usability and flexibility.
=> add Godot Engine to applications.json

config/applications.json
Adds development utility client for git repository management for GitHub/GitLab/BitBucket/etc.
=> Add GitKraken Client

functions/private/Get-WinUtilCheckBoxes.ps1, functions/private/Install-WinUtilProgramChoco.ps1, functions/private/Install-WinUtilProgramWinget.ps1, functions/public/Invoke-WPFInstall.ps1, functions/public/Invoke-WPFUnInstall.ps1
Separated Winget and Chocolatey setps when installing software add skip them when not needed
=> Install flow rework

config/applications.json, xaml/inputApp.xaml
I love the idea of installing multiple applications with wintuitls. 
But I was missing my new favorite package manager. This PR adds Pixi, which is a very fast software package manager built on top of the existing conda ecosystem. 
See https://pixi.sh
Eventually, this could replace Anaconda, and miniconda.
=> Add the Pixi package manger

wiki/Battery.md, wiki/Error-in-Winutil-MicroWin-during-ISO-mounting.md
Fixed some typos and removed passive voice in a few places in the wiki.
Saw to late that the ,md error got covered by https://github.com/ChrisTitusTech/winutil/pull/1965.
=> docs: minor spellchecking

functions/private/Invoke-WinUtilNumLock.ps1, winutil.ps1
Fixes numlock not being enabled before login screen.
=> Fix Numlock toggle

config/applications.json
- Replace Spaces with Tabs to make `applications.json` more consistent. (commit c86383b3324cdcafe55d1d28cf44887732e797fc)
- Corrected the Winget ID for 'AFFiNE' App Entry. (commit c2e5e0ad2ef523500b530af05e8598dc5f4a3963)
- Resolves: https://github.com/ChrisTitusTech/winutil/issues/2040
After doing a quick PR query over on [Microsoft's Winget Packages Repo](https://github.com/microsoft/winget-pkgs), the query being [this](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+AFFiNE+is%3Aclosed), it turns out the Winget ID for this program has changed since the PR that've added the app entry ([link to the PR](https://github.com/ChrisTitusTech/winutil/pull/1954)), here are the PRs that did this ID change:
1. https://github.com/microsoft/winget-pkgs/pull/153810
2. …
=> Simple improvements to 'applications.json' File

config/applications.json
Resolves: https://github.com/ChrisTitusTech/winutil/issues/2015
=> Add 'JoyToKey' and 'Wise Program Uninstaller' Apps into 'applications.json' File

config/applications.json
Resolves: https://github.com/ChrisTitusTech/winutil/issues/2067
=> Add 'croc' App to 'applications.json' File

config/applications.json
Satisfies some of the requests over on [#1782](https://github.com/ChrisTitusTech/winutil/issues/1782) Tracking list
=> Add 'TeraCopy' and 'Ambie White Noise' Apps into 'applications.json' File

config/applications.json
Added Plex Desktop for ease of install, description is simple "Front End for the plex media server"
=> Added Plex Desktop along side Plex Media Server

config/applications.json, winutil.ps1
This version is not really needed and adds bloat. I would make it merge into to the test branch. Love to see feedback as my first contribution to this brilliant project.
Have a Great day
=> Remove java 20

Compile.ps1
=> Fix Compile -Run always starting as PS5

config/applications.json
=> Added kicad

config/applications.json
=> Addition of Dropbox

config/applications.json
I love Mullvad VPN but I know VPNs in general are a hot debate ...
Since there is the Mullvad Browser in the ToolBox I think it is not too out of the question, but the decision lies on Chris.
- https://github.com/mullvad/mullvadvpn-app
=> Add Mullvad VPN to applications.json

config/applications.json
Fixed Version of PR: #2092, bc of app approval in [stream](https://youtu.be/qqYyWL5_R0U?t=1811).
=> Add Gitify to applications.json

functions/public/Invoke-WPFPanelAutologin.ps1
Resolves: https://github.com/ChrisTitusTech/winutil/issues/2180
=> Fix 'Invoke-WPFPanelAutologin.ps1' Public Function

config/applications.json
Requested in Issue https://github.com/ChrisTitusTech/winutil/issues/1782
=> Addition of Format Factory

config/applications.json
Changed the category of OrcaSlicer from "Multimedia Tools" to "Utilities" - Same as PrusaSlicer.
=> Moved OrcaSlicer to same category as PrusaSlicer

config/applications.json
Tweaks:
- Change Go title and description to make more sense
- Removed trying to install git along side some packages which causes issues (#2079). Dependencies should be installed automatically
- Update DevToys winget ID
=> Applications.json tweaks

config/applications.json
Add Application: Fastfetch
https://github.com/fastfetch-cli/fastfetch
Satisfies request made in #2158
=> Add 'Fastfetch' App into 'applications.json' File

config/applications.json
Satisfies a request made in Issue #1782 Tracking List.
=> Add 'TagScanner (Tag Scanner)' App into 'applications.json' File

config/applications.json
Satisfies a request made in Issue #1782 Tracking List.
=> Add 'Code With Mu (Mu Editor)' App into 'applications.json' File

config/tweaks.json
Tweak was not executing due to this.
=> Fixed tweak not running and typo

.gitattributes, functions/private/Get-TabXaml.ps1
Resolves: https://github.com/ChrisTitusTech/winutil/issues/2148
</br>
For more detail, look into the patches of each commit...
=> Fix New Line Character for 'winutil.ps1' File

config/applications.json
Satisfies a request made in #1782 Tracking List.
=> Add 'OFGB (Oh Frick Go Back)' App into 'applications.json' File

README.md
Added syntax highlighting and quotes to prevent the URL from being highlighted as well.
=> Attempt to simplify the launch command

KnownIssues.md, README.md
removed  
`Windows Insider Builds not installing: Telemetry needs to be enabled`
`Explorer no longer launches: Go to Control Panel, File Explorer Options, Change the 'Open File Explorer to' option to 'This PC'`
as this issues got fixed
=> updated KnownIssues.md

KnownIssues.md, README.md
Hey Chris, resolving the merge conflict made a part redundant, I removed it.
Did some stuff and now it isn't redundant and able to merge
=> Known Issues: Removed redundancy caused by resolving the merge conflict.

CONTRIBUTING.md, README.md
Moved two sections from `README.md` file into the new `CONTRIBUTING.md` file, condensing the length of `README` a little bit.
**EDIT**: This was request in an Issue as well, [Link to the Issue](https://github.com/ChrisTitusTech/winutil/issues/2115).
=> Add 'CONTRIBUTING.md' File

KnownIssues.md, README.md
welp, took some inspiration from #2214 and changed all ps code snippeds in .md files that I've found to have the right syntax highlighting.
=> fix syntax highlighting in .MDs

config/applications.json
An open source video with regular updates 
https://shotcut.org/
https://github.com/mltframework/shotcut
=> Add "Shotcut" in applications

functions/private/ConvertTo-Icon.ps1, functions/public/Invoke-WPFShortcut.ps1
Resolves: https://github.com/ChrisTitusTech/winutil/issues/2241
=> Fix Icon Support for Shortcut Creation

functions/public/Invoke-WPFButton.ps1, functions/public/Invoke-WPFUltimatePerformance.ps1
closes #2056
closes #2265
- fixed grammer to represent action taken, not the state switching to.
- rewrote function
- made function more compact
I've testet it on multiple machines, it worked every time for me, I also had the Issue before.
=> Fix: Ultimate Performance Plan

functions/private/Invoke-WinUtilTaskbarSearch.ps1
See the PR Title.
Resolves: https://github.com/ChrisTitusTech/winutil/issues/2245
=> Fix Typo in 'Invoke-WinUtilTaskbarSearch' Private Function

config/applications.json
Add Application "Modern Flyouts"
https://github.com/ModernFlyouts-Community/ModernFlyouts
closes #2291
=> Add app: Modern Flyouts

.github/PULL_REQUEST_TEMPLATE.mb, winutil.ps1
This will help with making PR's easier to read based on what is happening in that PR and what issue is being resolved.
=> Adds PR template

config/applications.json
Changed Kicad to "Multimedia Tools" as all the other CAD software.
=> Change Kicad category

config/dns.json, functions/private/Set-WinUtilDNS.ps1
The DNS tweak also affects IPv6.
I had to eliminate Level3 as an option because i could not find its IPv6 address.
I also added AdGuard DNS as an option.
Hope I've done the pull request well this time!
=> Added IPv6 DNS

.github/workflows/createchangelog.yml
Create createchangelog.yml for docs page 
Create createchangelog.yml for docs page so it automates releases on the docs
Can't test till all PR's are done for docs.
To automate updates page on docs
No
=> Create createchangelog.yml for docs page

README.md
Adds Community Discord to ReadMe file
Adds Community Discord to ReadMe file
None required
None
No
=> Adds Community Discord to ReadMe file

config/applications.json
Addition of fork
The changes that where made was the additon of the fork application to the applications.json file.
I have tested that when I go to install the program it installs with no errors.
The impact on this is so people can fine a new git software for them to use.
- Resolves  part of #1782 
No
=> Addition of Fork

config/tweaks.json, functions/private/Get-WinUtilToggleStatus.ps1, functions/private/Invoke-WinUtilHiddenFiles.ps1, functions/public/Invoke-WPFToggle.ps1
Hidden File Tweaks
Works on adding hidden file tweaks.
Went to test but was kicked back with loads of errors. Doing this PR as a draft for other contrinutors to see and help fix.
Adds a new tweak to the utility
- Resolves #2317 when fixed.
Kicks back loads of errors
=> Hidden File Tweaks

config/applications.json
A sysinternals app for screen zoom, annotation, and recording tool for technical presentations and demos.
- https://learn.microsoft.com/en-us/sysinternals/downloads/zoomit
I use it because it has minimal impact and is very simple but does the job better than some others.
=> Add Application: ZoomIt

config/tweaks.json
Do & undo straightup does not work.
- I changed the script a bit so it works now.
- It fixes the issue but isn't the best way of fixing it, the usual way of doing it gave warnings and did also not work.
- Will follow up on it if I have time, this makes it work
- Resolves #2330
=> Fix: End Task with right click

.github/workflows/pre-release.yaml, .github/workflows/release.yaml, README.md
- Modifies the Theming of the Badges on the Readme to look the same
- Changes the Download Counter on the Readme to show Total Downloads of ALL Releases combined
- Modifies the Release workflow of pre-release and release to add a specific download counter to their page that only displays the count for the specific version
=> Optimize badges

.github/workflows/createchangelog.yml
Fixes an issue with create changelog not working
Fixes an issue with create changelog not working
None avaliable
None
- Resolves no Issues's
[What discussion is related to this PR (if any)]
- Discussion no Discussion's
No
=> Fixes an issue with create changelog not working

.github/PULL_REQUEST_TEMPLATE.md
Updates PR template so disscussion and issue is on the same line.
Updates PR template so disscussion and issue is on the same line.
None avaliable
None as only updates a template to make it easier
- Resolves #
[What discussion is related to this PR (if any)]
- Discussion: #
No
=> Updates PR template so disscussion and issue is on the same line.

.github/workflows/close-discussion.yml
Update close-discussion.yml so it detects based on new previous PR
Update close-discussion.yml so it detects based on new previous PR
None avaliable till merged
Low as simplifies code
- Resolves #
[What discussion is related to this PR (if any)]
- Discussion: #
No
=> Update close-discussion.yml so it detects based on new previous PR

config/tweaks.json
Fix typo in hybernation tweak.
Changed the word 'stadby' to 'standby'
I did no testking.
Not much.
None
None
=> Fix typo in hybernation tweak.

config/applications.json
Fix grammer in application description
- Resolves #2436
=> fix OFGB typo

config/tweaks.json
Typo fix in hibernation tweak
https://github.com/ChrisTitusTech/winutil/issues/2431
Changes "stadby" to "standby"
None
None
- Resolves #2431
None
=> Update tweaks.json to correct stadby -> standby

config/applications.json
Added Gitbutler
Gitbutler is a git client for simultaneous branches on top of your existing workflow.
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behaviour.]
- Resolves #
[Any additional information that reviewers should be aware of.]
=> Added Gitbutler

functions/public/Invoke-WPFMicrowin.ps1
(Same as title)
This PR changes the way OSCDIMG is launched, going back to a simple one-liner after the change introduced in #1346, while still keeping the custom location stuff.
The new one-liner features the `-PassThru` flag, which is required to get the exit code in this implementation. The exit code is later set to the unused `$LASTEXITCODE` variable, which now has a new purpose:
If the error code is not 0, this PR will also try to grab a description of the error code in the system language from the Windows APIs. Here is an example:
> [!NOTE]
> As stated in the source code, it WILL NOT throw an exception. [Here](https://github.com/CodingWonders/DISMTools/blob/b96abd7138df83a4fa1b8bcdec6eae879b1810eb/Panels/DoWork/ProgressPanel.vb#L6319-L6325) is another example of that feature, from …
=> Get OSCDIMG exit code and show an error description

config/applications.json
Update UniGetUI description
(not exactly sure which one it is)
I noticed that the description of UniGetUI still said "WingetUI," so I updated it. I also fixed the capitalization.
=> Update UniGetUI description

docs/contribute.md, docs/index.md
<details><summary>Before</summary>
<p>
</p>
</details> 
<details><summary>After</summary>
<p>
</p>
</details>
=> Fix some bullet points in 'contribute.md' file as well as some improvments to the graph

functions/private/ConvertTo-Icon.ps1
[[Provide a succinct and descriptive title for the pull request.]](chore: update ConvertTo-Icon.ps1)
paramter -> parameter
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behaviour.]
- Resolves #
[Any additional information that reviewers should be aware of.]
=> chore: update ConvertTo-Icon.ps1

windev.ps1
the link is invalid, so i changed it so something that works.
tested, worked
- Resolves #2536
=> Fix windev launch issue

functions/private/Invoke-MicroWin-Helper.ps1, functions/public/Invoke-WPFGetIso.ps1, functions/public/Invoke-WPFMicrowin.ps1
(Same as title)
This PR adds quotation marks to paths. This fixes issues about file paths not existing if they contain spaces
This was tested with a Windows 11 21H2 image. MicroWin processing still works.
Reliability improvements
- Resolves #2551 
No documentation changes required
=> Add quotes to paths

functions/public/Invoke-WPFMicrowin.ps1
Prevent expedited apps install (Microwin)
Prevent Windows Update Installing so called Expedited Apps
Less extra bloat after a windows update 
- Resolves #2453
=> Microwin: Prevent expedited apps install

.github/workflows/github-pages.yaml
Auto pushes docs
Auto pushes docs when docs related files are changed/locations.
None done.
Big for when PR's are merged.
Nope
=> Auto pushes docs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Comment out help from issue templates. User can still see them while editing the description of the issue, but viewers don't see it.
- people will directly see how much was really filled out and don't have to read the help that was meant for the issue creator.
=> [Issue Template] Comment out help

functions/private/Update-WinUtilProgramWinget.ps1, scripts/start.ps1
Improving log by seperating them by date, I think that helps when having to look at them and running winutil a lot.
- works, took inspiration from my old script
=> Improve Transcript

.github/workflows/github-pages.yaml
Update github-pages.yaml to look at the CONTRIBUTING.mb file.
Update github-pages.yaml to look at the CONTRIBUTING.mb file.
None required
Makes sure docs are always up to date.
No
=> Update github-pages.yaml to look at the CONTRIBUTING.mb file.

overrides/main.html
Update main.html to fix spelling
Update main.html to fix spelling
None
Fixes spelling mistake in docs.
No
=> Update main.html to fix spelling

xaml/inputXML.xaml
Patches changes related to PR #2608 
After these changes, the clear button in Tweaks section work properly.
=> Hot Fix for clear button in Tweaks Section

functions/public/Invoke-WPFGetIso.ps1
While reading an Issue i saw an outdated link thrown as error message in the shell. The issue itself has nothing to do with this PR, therefore I will not link it.
- update wiki link to docs link
- change write error to write host for this message, bc write-host has "more support" for links, the color stays red
worked fine
=> Update microwin wiki link

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- added "bug" to bug template
- added "enhancement" to feature request template
- not tested
This way it is easier to categorize the entrys in the issue tab, and know what might be a more important issue entry to look at.
=> Add labels to Issue templates

config/feature.json, functions/private/Invoke-WinUtilpsProfile.ps1, functions/public/Invoke-WPFButton.ps1
- add button to config for installing CTT Profile setup
- had this PR laying around for some time, updated it and published PR
tested & handled for following cases:
- ps7 installed & updated profile
- ps7 installed & outdated profile
- ps7 installed, not used & updated profile
- ps7 installed, not used & outdated profile
- ps7 not installed
=> CTT Powershell Profile 

functions/private/Get-WinUtilToggleStatus.ps1
Refactor: functions/private/Get-WinUtilToggleStatus.ps1
Simplify return statements and make them shorter
Test by running each if statement before and after refactoring to ensure same bahaviour
Make code shorter and easier to read
- Resolves #
=> refac(toggle status): simplify return statements

.github/workflows/close-issue-command.yaml
Update close-issue-command.yaml to allow not planned closing and reopening issues
Tested in LinUtil
Allows new ways when sorting out issues.
N/A
=> Update close-issue-command.yaml to allow not planned closing and reopening issues

scripts/main.ps1
Do not include the prefer choco checkbox in the filter search results 
Resolves #2774
=> Fix prefer choco visibility

functions/public/Invoke-WPFUnInstall.ps1
Reverts ChrisTitusTech/winutil#2797
=> Revert "refac(invoke-wpfuninstall.ps1): remove null assignments and simplify taskbaritem invocation"

windev.ps1
Update the text if no pre-release is found and change the text color from red to yellow to mark this as a warning instead of an error
- Resolves #2946
=> Small update to windev.ps1

.github/mkdocs.yml
=> Update mkdocs.yml part 2/2

docs/userguide.md
- add adguard
- add dns0
- remove Level3
- change google link from german to english
- Resolves #2854
=> [DOCS] Update Userguide (DNS)

.github/workflows/close-old-issues.yaml
> stale + closing message contains outdated time (it is not 7 days anymore)
- remove mention of how long it has been and simplify the message.
=> [CI/CD] close old issue missinformation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- add  issue validation inspired by https://github.com/ChrisTitusTech/linutil/pull/459
- standardize capitalisation of characters in titles
- update `feature request` to use headers instead of bold text for titles
=> [Issue Template] Add Validation

.github/workflows/issue-slash-commands.yaml, functions/public/Invoke-WPFButton.ps1, functions/public/Invoke-WPFFixesUpdate.ps1, functions/public/Invoke-WPFUIElements.ps1, scripts/main.ps1, xaml/inputXML.xaml
This improves the reset of windows update and language around Windows Update. Also added placeholders to give the user more information about Windows update in the future. 
Also, removed some LLM BS that made its way into the code.
=> Fix language and Logic to Updates

config/applications.json
- Updated the winget package identifier for FxSound from `FxSoundLLC.FxSound` to `FxSound.FxSound`.
- Updated the description for FxSound in the `applications.json` file, detailing its features such as boosting sound quality, volume, and bass with an equalizer and effects.
The winget package identifier for FxSound had become outdated, which caused installation failures. This change ensures that the correct package identifier is used, allowing users to successfully install FxSound via winget. The description update provides users with better context about the software’s features directly from the FxSound website
=> Fix winget command and update FxSound description

config/applications.json
- Added ability to install Zen Browser
- tested winget -> worked
- tested choco -> needs --pre flag, meaning i removed it
=> [APP addition] Zen Browser

.gitignore, overrides/main.html
Thanks to @MyDrift-user & @Marterich work on the app install refactor in PR #2859, we can add new apps into the list.
Also I've updated the `.gitignore` file, checkout the commit message for it (commit 2952b81d31b44f1378bf948ed5e5bf828576895d)
=> [DOCS] Remove old Announcement about not adding any new applications to the app list

config/feature.json, functions/public/Invoke-WPFButton.ps1, functions/public/Invoke-WPFControlPanel.ps1
Adds a new Button called "God Mode" to the Legacy Panels  that opens 
...
can  you guess it
...
the God Mode
- Resolves #3258
=> Add God Mode panel to Legacy Windows Panels

config/applications.json
Update the description of Prism Launcher to accurately reflect what it is (the current description is misleading).
Works as expected
Purely textual
=> Correct description for Prism Launcher

functions/private/Initalize-InstallAppEntry.ps1
- right click an application to unselect all other and select that one you right clicked
- tested -> works as expected
- example usage: get installed apps, right click one to easily have the view of the installed apps and only select some to uninstall.
=> Action on application right click 

config/applications.json
=> Fix Gimp Winget Package

config/tweaks.json
This is a fix to a minor issue regarding commas at the end of the tweaks JSON. Even though compilation gets rid of this issue, we should fix it in the source.
Testing has concluded successfully.
Bugs fixed in the source
No issues are related to this on GitHub, but something that was talked about a bit on the Discord server.
No documentation changes are required
=> [Tweaks] Remove trailing commas at the end of the JSON

README.md, config/feature.json, config/tweaks.json
Update all links which uses https://christitustech.github.io/winutil/ to the new docs website https://winutil.christitus.com/
Compiled winutil and everything Works as expected.
This's help users see the latest website which'll help on feedback and for completely migrating the docs to a separate repo.
This's a temporary fix until the `devdocs` tool script is updated, as it's currently broken (see [Issue 3237](https://github.com/ChrisTitusTech/winutil/issues/3237) for more info).
The changes to the URLs in `config` folder is done finding `https://christitustech.github.io/winutil/` and replacing it with `https://winutil.christitus.com/`.
The following script looks for `link` field in the json, and changes it to a _lower string version_, done for both `tweaks.json` and `feature.json` files. …
=> Update documentation links to the new website https://winutil.christitus.com/

config/applications.json
- FFmpeg can not be uninstalled using winget for some reason. that has now been the case for a long time so I thought about adding a little note to the package entry.
- Resolves #2569
=> [App FFmpeg] add Note

functions/public/Invoke-WPFFixesNetwork.ps1, functions/public/Invoke-WPFFixesUpdate.ps1, functions/public/Invoke-WPFFixesWinget.ps1, functions/public/Invoke-WPFSystemRepair.ps1
- Improve Error Handling + add Taskbarprogress to some Fixes
- testet, works
- Got into it thanks to #2951
=> [Fixes] Improve Error Handling + UI

config/tweaks.json
- adds availability to toggle Multiplane Overlay which is a feature introduced in Windows 8.1 which can cause issues with GPUs.
- Resolves #3107 (explains the situation pretty good)
- Resolves #564
- https://learn.microsoft.com/en-us/windows-hardware/drivers/display/multiplane-overlay-support
- https://www.reddit.com/r/Amd/comments/yvyqc7/disabling_multiplane_overlay_mpo_fixed_all/
- https://nvidia.custhelp.com/app/answers/detail/a_id/5157/~/after-updating-to-nvidia-game-ready-driver-461.09-or-newer%2C-some-desktop-apps
=> [Toggle] addition to toggle Multiplane Overlay 

.gitignore, scripts/main.ps1
Fixes issues with Blockades
Tested locally
- Resolves #3528
=> Blockade fix

functions/public/Invoke-WPFInstall.ps1
This PR fixes an issue about a missing method in an object type
Assuming the rest of the code works, this should work.
None
None
None
=> [Fix] SecureString does not have Close method

functions/private/Install-WinUtilWinget.ps1
Self-explanatory.
This should work.
- Resolves countless issues
None
=> [Applications] Possible fix for cmdlet

functions/public/Invoke-WPFUpdatesdefault.ps1, functions/public/Invoke-WPFUpdatesdisable.ps1
Multiple users have expressed a desire to disable updates permanently. The current windows update disable gets removed automatically on windows update repair and restarts. 
The new method here will break and disable it FOREVER! Note: This is a very aggressive approach, but given the problems with recent updates breaking hardware, it is a needed addition.
- Resolves #3567 
- Resolves #3550 
- Resolves #3214 
- Resolves #3156 
- Resolves #3116 
- Resolves #3106 
- Resolves #2997 
- Resolves #2962 
Update to Default Windows settings and reset to also undo the disable for those that need to re-enable or run windows update.
=> Install Windows Update Blocker

config/applications.json
This PR changes some things in the app lists:
- NTLite has been added to the list of apps as another DISM utility to give the user some choice
- Both DISMTools and NTLite have been moved to a new section so they can be identified more easily by what they do, and because the former is not a tool made by either Microsoft or Sysinternals. The former now has its description pulled from WinGet (and summarized using Copilot)
- Em-dashes in some app descriptions have been replaced with semicolons to avoid question marks in tooltips
Testing has concluded successfully.
Better categorization of some apps
None
None
=> [Applications] DISM utility changes, app description fixes
